// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package microvm_image

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if len(a.ko.Spec.AdditionalOsCapabilities) != len(b.ko.Spec.AdditionalOsCapabilities) {
		delta.Add("Spec.AdditionalOsCapabilities", a.ko.Spec.AdditionalOsCapabilities, b.ko.Spec.AdditionalOsCapabilities)
	} else if len(a.ko.Spec.AdditionalOsCapabilities) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.AdditionalOsCapabilities, b.ko.Spec.AdditionalOsCapabilities) {
			delta.Add("Spec.AdditionalOsCapabilities", a.ko.Spec.AdditionalOsCapabilities, b.ko.Spec.AdditionalOsCapabilities)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.BaseImageARN, b.ko.Spec.BaseImageARN) {
		delta.Add("Spec.BaseImageARN", a.ko.Spec.BaseImageARN, b.ko.Spec.BaseImageARN)
	} else if a.ko.Spec.BaseImageARN != nil && b.ko.Spec.BaseImageARN != nil {
		if *a.ko.Spec.BaseImageARN != *b.ko.Spec.BaseImageARN {
			delta.Add("Spec.BaseImageARN", a.ko.Spec.BaseImageARN, b.ko.Spec.BaseImageARN)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.BaseImageVersion, b.ko.Spec.BaseImageVersion) {
		delta.Add("Spec.BaseImageVersion", a.ko.Spec.BaseImageVersion, b.ko.Spec.BaseImageVersion)
	} else if a.ko.Spec.BaseImageVersion != nil && b.ko.Spec.BaseImageVersion != nil {
		if *a.ko.Spec.BaseImageVersion != *b.ko.Spec.BaseImageVersion {
			delta.Add("Spec.BaseImageVersion", a.ko.Spec.BaseImageVersion, b.ko.Spec.BaseImageVersion)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.BuildRoleARN, b.ko.Spec.BuildRoleARN) {
		delta.Add("Spec.BuildRoleARN", a.ko.Spec.BuildRoleARN, b.ko.Spec.BuildRoleARN)
	} else if a.ko.Spec.BuildRoleARN != nil && b.ko.Spec.BuildRoleARN != nil {
		if *a.ko.Spec.BuildRoleARN != *b.ko.Spec.BuildRoleARN {
			delta.Add("Spec.BuildRoleARN", a.ko.Spec.BuildRoleARN, b.ko.Spec.BuildRoleARN)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.BuildRoleRef, b.ko.Spec.BuildRoleRef) {
		delta.Add("Spec.BuildRoleRef", a.ko.Spec.BuildRoleRef, b.ko.Spec.BuildRoleRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.CodeArtifact, b.ko.Spec.CodeArtifact) {
		delta.Add("Spec.CodeArtifact", a.ko.Spec.CodeArtifact, b.ko.Spec.CodeArtifact)
	} else if a.ko.Spec.CodeArtifact != nil && b.ko.Spec.CodeArtifact != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.CodeArtifact.URI, b.ko.Spec.CodeArtifact.URI) {
			delta.Add("Spec.CodeArtifact.URI", a.ko.Spec.CodeArtifact.URI, b.ko.Spec.CodeArtifact.URI)
		} else if a.ko.Spec.CodeArtifact.URI != nil && b.ko.Spec.CodeArtifact.URI != nil {
			if *a.ko.Spec.CodeArtifact.URI != *b.ko.Spec.CodeArtifact.URI {
				delta.Add("Spec.CodeArtifact.URI", a.ko.Spec.CodeArtifact.URI, b.ko.Spec.CodeArtifact.URI)
			}
		}
	}
	if len(a.ko.Spec.CPUConfigurations) != len(b.ko.Spec.CPUConfigurations) {
		delta.Add("Spec.CPUConfigurations", a.ko.Spec.CPUConfigurations, b.ko.Spec.CPUConfigurations)
	} else if len(a.ko.Spec.CPUConfigurations) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.CPUConfigurations, b.ko.Spec.CPUConfigurations) {
			delta.Add("Spec.CPUConfigurations", a.ko.Spec.CPUConfigurations, b.ko.Spec.CPUConfigurations)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Description, b.ko.Spec.Description) {
		delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
	} else if a.ko.Spec.Description != nil && b.ko.Spec.Description != nil {
		if *a.ko.Spec.Description != *b.ko.Spec.Description {
			delta.Add("Spec.Description", a.ko.Spec.Description, b.ko.Spec.Description)
		}
	}
	if len(a.ko.Spec.EgressNetworkConnectors) != len(b.ko.Spec.EgressNetworkConnectors) {
		delta.Add("Spec.EgressNetworkConnectors", a.ko.Spec.EgressNetworkConnectors, b.ko.Spec.EgressNetworkConnectors)
	} else if len(a.ko.Spec.EgressNetworkConnectors) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.EgressNetworkConnectors, b.ko.Spec.EgressNetworkConnectors) {
			delta.Add("Spec.EgressNetworkConnectors", a.ko.Spec.EgressNetworkConnectors, b.ko.Spec.EgressNetworkConnectors)
		}
	}
	if len(a.ko.Spec.EnvironmentVariables) != len(b.ko.Spec.EnvironmentVariables) {
		delta.Add("Spec.EnvironmentVariables", a.ko.Spec.EnvironmentVariables, b.ko.Spec.EnvironmentVariables)
	} else if len(a.ko.Spec.EnvironmentVariables) > 0 {
		if !ackcompare.MapStringStringPEqual(a.ko.Spec.EnvironmentVariables, b.ko.Spec.EnvironmentVariables) {
			delta.Add("Spec.EnvironmentVariables", a.ko.Spec.EnvironmentVariables, b.ko.Spec.EnvironmentVariables)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Hooks, b.ko.Spec.Hooks) {
		delta.Add("Spec.Hooks", a.ko.Spec.Hooks, b.ko.Spec.Hooks)
	} else if a.ko.Spec.Hooks != nil && b.ko.Spec.Hooks != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.Hooks.MicrovmHooks, b.ko.Spec.Hooks.MicrovmHooks) {
			delta.Add("Spec.Hooks.MicrovmHooks", a.ko.Spec.Hooks.MicrovmHooks, b.ko.Spec.Hooks.MicrovmHooks)
		} else if a.ko.Spec.Hooks.MicrovmHooks != nil && b.ko.Spec.Hooks.MicrovmHooks != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.Hooks.MicrovmHooks.Resume, b.ko.Spec.Hooks.MicrovmHooks.Resume) {
				delta.Add("Spec.Hooks.MicrovmHooks.Resume", a.ko.Spec.Hooks.MicrovmHooks.Resume, b.ko.Spec.Hooks.MicrovmHooks.Resume)
			} else if a.ko.Spec.Hooks.MicrovmHooks.Resume != nil && b.ko.Spec.Hooks.MicrovmHooks.Resume != nil {
				if *a.ko.Spec.Hooks.MicrovmHooks.Resume != *b.ko.Spec.Hooks.MicrovmHooks.Resume {
					delta.Add("Spec.Hooks.MicrovmHooks.Resume", a.ko.Spec.Hooks.MicrovmHooks.Resume, b.ko.Spec.Hooks.MicrovmHooks.Resume)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.Hooks.MicrovmHooks.ResumeTimeoutInSeconds, b.ko.Spec.Hooks.MicrovmHooks.ResumeTimeoutInSeconds) {
				delta.Add("Spec.Hooks.MicrovmHooks.ResumeTimeoutInSeconds", a.ko.Spec.Hooks.MicrovmHooks.ResumeTimeoutInSeconds, b.ko.Spec.Hooks.MicrovmHooks.ResumeTimeoutInSeconds)
			} else if a.ko.Spec.Hooks.MicrovmHooks.ResumeTimeoutInSeconds != nil && b.ko.Spec.Hooks.MicrovmHooks.ResumeTimeoutInSeconds != nil {
				if *a.ko.Spec.Hooks.MicrovmHooks.ResumeTimeoutInSeconds != *b.ko.Spec.Hooks.MicrovmHooks.ResumeTimeoutInSeconds {
					delta.Add("Spec.Hooks.MicrovmHooks.ResumeTimeoutInSeconds", a.ko.Spec.Hooks.MicrovmHooks.ResumeTimeoutInSeconds, b.ko.Spec.Hooks.MicrovmHooks.ResumeTimeoutInSeconds)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.Hooks.MicrovmHooks.Run, b.ko.Spec.Hooks.MicrovmHooks.Run) {
				delta.Add("Spec.Hooks.MicrovmHooks.Run", a.ko.Spec.Hooks.MicrovmHooks.Run, b.ko.Spec.Hooks.MicrovmHooks.Run)
			} else if a.ko.Spec.Hooks.MicrovmHooks.Run != nil && b.ko.Spec.Hooks.MicrovmHooks.Run != nil {
				if *a.ko.Spec.Hooks.MicrovmHooks.Run != *b.ko.Spec.Hooks.MicrovmHooks.Run {
					delta.Add("Spec.Hooks.MicrovmHooks.Run", a.ko.Spec.Hooks.MicrovmHooks.Run, b.ko.Spec.Hooks.MicrovmHooks.Run)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.Hooks.MicrovmHooks.RunTimeoutInSeconds, b.ko.Spec.Hooks.MicrovmHooks.RunTimeoutInSeconds) {
				delta.Add("Spec.Hooks.MicrovmHooks.RunTimeoutInSeconds", a.ko.Spec.Hooks.MicrovmHooks.RunTimeoutInSeconds, b.ko.Spec.Hooks.MicrovmHooks.RunTimeoutInSeconds)
			} else if a.ko.Spec.Hooks.MicrovmHooks.RunTimeoutInSeconds != nil && b.ko.Spec.Hooks.MicrovmHooks.RunTimeoutInSeconds != nil {
				if *a.ko.Spec.Hooks.MicrovmHooks.RunTimeoutInSeconds != *b.ko.Spec.Hooks.MicrovmHooks.RunTimeoutInSeconds {
					delta.Add("Spec.Hooks.MicrovmHooks.RunTimeoutInSeconds", a.ko.Spec.Hooks.MicrovmHooks.RunTimeoutInSeconds, b.ko.Spec.Hooks.MicrovmHooks.RunTimeoutInSeconds)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.Hooks.MicrovmHooks.Suspend, b.ko.Spec.Hooks.MicrovmHooks.Suspend) {
				delta.Add("Spec.Hooks.MicrovmHooks.Suspend", a.ko.Spec.Hooks.MicrovmHooks.Suspend, b.ko.Spec.Hooks.MicrovmHooks.Suspend)
			} else if a.ko.Spec.Hooks.MicrovmHooks.Suspend != nil && b.ko.Spec.Hooks.MicrovmHooks.Suspend != nil {
				if *a.ko.Spec.Hooks.MicrovmHooks.Suspend != *b.ko.Spec.Hooks.MicrovmHooks.Suspend {
					delta.Add("Spec.Hooks.MicrovmHooks.Suspend", a.ko.Spec.Hooks.MicrovmHooks.Suspend, b.ko.Spec.Hooks.MicrovmHooks.Suspend)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.Hooks.MicrovmHooks.SuspendTimeoutInSeconds, b.ko.Spec.Hooks.MicrovmHooks.SuspendTimeoutInSeconds) {
				delta.Add("Spec.Hooks.MicrovmHooks.SuspendTimeoutInSeconds", a.ko.Spec.Hooks.MicrovmHooks.SuspendTimeoutInSeconds, b.ko.Spec.Hooks.MicrovmHooks.SuspendTimeoutInSeconds)
			} else if a.ko.Spec.Hooks.MicrovmHooks.SuspendTimeoutInSeconds != nil && b.ko.Spec.Hooks.MicrovmHooks.SuspendTimeoutInSeconds != nil {
				if *a.ko.Spec.Hooks.MicrovmHooks.SuspendTimeoutInSeconds != *b.ko.Spec.Hooks.MicrovmHooks.SuspendTimeoutInSeconds {
					delta.Add("Spec.Hooks.MicrovmHooks.SuspendTimeoutInSeconds", a.ko.Spec.Hooks.MicrovmHooks.SuspendTimeoutInSeconds, b.ko.Spec.Hooks.MicrovmHooks.SuspendTimeoutInSeconds)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.Hooks.MicrovmHooks.Terminate, b.ko.Spec.Hooks.MicrovmHooks.Terminate) {
				delta.Add("Spec.Hooks.MicrovmHooks.Terminate", a.ko.Spec.Hooks.MicrovmHooks.Terminate, b.ko.Spec.Hooks.MicrovmHooks.Terminate)
			} else if a.ko.Spec.Hooks.MicrovmHooks.Terminate != nil && b.ko.Spec.Hooks.MicrovmHooks.Terminate != nil {
				if *a.ko.Spec.Hooks.MicrovmHooks.Terminate != *b.ko.Spec.Hooks.MicrovmHooks.Terminate {
					delta.Add("Spec.Hooks.MicrovmHooks.Terminate", a.ko.Spec.Hooks.MicrovmHooks.Terminate, b.ko.Spec.Hooks.MicrovmHooks.Terminate)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.Hooks.MicrovmHooks.TerminateTimeoutInSeconds, b.ko.Spec.Hooks.MicrovmHooks.TerminateTimeoutInSeconds) {
				delta.Add("Spec.Hooks.MicrovmHooks.TerminateTimeoutInSeconds", a.ko.Spec.Hooks.MicrovmHooks.TerminateTimeoutInSeconds, b.ko.Spec.Hooks.MicrovmHooks.TerminateTimeoutInSeconds)
			} else if a.ko.Spec.Hooks.MicrovmHooks.TerminateTimeoutInSeconds != nil && b.ko.Spec.Hooks.MicrovmHooks.TerminateTimeoutInSeconds != nil {
				if *a.ko.Spec.Hooks.MicrovmHooks.TerminateTimeoutInSeconds != *b.ko.Spec.Hooks.MicrovmHooks.TerminateTimeoutInSeconds {
					delta.Add("Spec.Hooks.MicrovmHooks.TerminateTimeoutInSeconds", a.ko.Spec.Hooks.MicrovmHooks.TerminateTimeoutInSeconds, b.ko.Spec.Hooks.MicrovmHooks.TerminateTimeoutInSeconds)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.Hooks.MicrovmImageHooks, b.ko.Spec.Hooks.MicrovmImageHooks) {
			delta.Add("Spec.Hooks.MicrovmImageHooks", a.ko.Spec.Hooks.MicrovmImageHooks, b.ko.Spec.Hooks.MicrovmImageHooks)
		} else if a.ko.Spec.Hooks.MicrovmImageHooks != nil && b.ko.Spec.Hooks.MicrovmImageHooks != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.Hooks.MicrovmImageHooks.Ready, b.ko.Spec.Hooks.MicrovmImageHooks.Ready) {
				delta.Add("Spec.Hooks.MicrovmImageHooks.Ready", a.ko.Spec.Hooks.MicrovmImageHooks.Ready, b.ko.Spec.Hooks.MicrovmImageHooks.Ready)
			} else if a.ko.Spec.Hooks.MicrovmImageHooks.Ready != nil && b.ko.Spec.Hooks.MicrovmImageHooks.Ready != nil {
				if *a.ko.Spec.Hooks.MicrovmImageHooks.Ready != *b.ko.Spec.Hooks.MicrovmImageHooks.Ready {
					delta.Add("Spec.Hooks.MicrovmImageHooks.Ready", a.ko.Spec.Hooks.MicrovmImageHooks.Ready, b.ko.Spec.Hooks.MicrovmImageHooks.Ready)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.Hooks.MicrovmImageHooks.ReadyTimeoutInSeconds, b.ko.Spec.Hooks.MicrovmImageHooks.ReadyTimeoutInSeconds) {
				delta.Add("Spec.Hooks.MicrovmImageHooks.ReadyTimeoutInSeconds", a.ko.Spec.Hooks.MicrovmImageHooks.ReadyTimeoutInSeconds, b.ko.Spec.Hooks.MicrovmImageHooks.ReadyTimeoutInSeconds)
			} else if a.ko.Spec.Hooks.MicrovmImageHooks.ReadyTimeoutInSeconds != nil && b.ko.Spec.Hooks.MicrovmImageHooks.ReadyTimeoutInSeconds != nil {
				if *a.ko.Spec.Hooks.MicrovmImageHooks.ReadyTimeoutInSeconds != *b.ko.Spec.Hooks.MicrovmImageHooks.ReadyTimeoutInSeconds {
					delta.Add("Spec.Hooks.MicrovmImageHooks.ReadyTimeoutInSeconds", a.ko.Spec.Hooks.MicrovmImageHooks.ReadyTimeoutInSeconds, b.ko.Spec.Hooks.MicrovmImageHooks.ReadyTimeoutInSeconds)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.Hooks.MicrovmImageHooks.Validate, b.ko.Spec.Hooks.MicrovmImageHooks.Validate) {
				delta.Add("Spec.Hooks.MicrovmImageHooks.Validate", a.ko.Spec.Hooks.MicrovmImageHooks.Validate, b.ko.Spec.Hooks.MicrovmImageHooks.Validate)
			} else if a.ko.Spec.Hooks.MicrovmImageHooks.Validate != nil && b.ko.Spec.Hooks.MicrovmImageHooks.Validate != nil {
				if *a.ko.Spec.Hooks.MicrovmImageHooks.Validate != *b.ko.Spec.Hooks.MicrovmImageHooks.Validate {
					delta.Add("Spec.Hooks.MicrovmImageHooks.Validate", a.ko.Spec.Hooks.MicrovmImageHooks.Validate, b.ko.Spec.Hooks.MicrovmImageHooks.Validate)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.Hooks.MicrovmImageHooks.ValidateTimeoutInSeconds, b.ko.Spec.Hooks.MicrovmImageHooks.ValidateTimeoutInSeconds) {
				delta.Add("Spec.Hooks.MicrovmImageHooks.ValidateTimeoutInSeconds", a.ko.Spec.Hooks.MicrovmImageHooks.ValidateTimeoutInSeconds, b.ko.Spec.Hooks.MicrovmImageHooks.ValidateTimeoutInSeconds)
			} else if a.ko.Spec.Hooks.MicrovmImageHooks.ValidateTimeoutInSeconds != nil && b.ko.Spec.Hooks.MicrovmImageHooks.ValidateTimeoutInSeconds != nil {
				if *a.ko.Spec.Hooks.MicrovmImageHooks.ValidateTimeoutInSeconds != *b.ko.Spec.Hooks.MicrovmImageHooks.ValidateTimeoutInSeconds {
					delta.Add("Spec.Hooks.MicrovmImageHooks.ValidateTimeoutInSeconds", a.ko.Spec.Hooks.MicrovmImageHooks.ValidateTimeoutInSeconds, b.ko.Spec.Hooks.MicrovmImageHooks.ValidateTimeoutInSeconds)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.Hooks.Port, b.ko.Spec.Hooks.Port) {
			delta.Add("Spec.Hooks.Port", a.ko.Spec.Hooks.Port, b.ko.Spec.Hooks.Port)
		} else if a.ko.Spec.Hooks.Port != nil && b.ko.Spec.Hooks.Port != nil {
			if *a.ko.Spec.Hooks.Port != *b.ko.Spec.Hooks.Port {
				delta.Add("Spec.Hooks.Port", a.ko.Spec.Hooks.Port, b.ko.Spec.Hooks.Port)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Logging, b.ko.Spec.Logging) {
		delta.Add("Spec.Logging", a.ko.Spec.Logging, b.ko.Spec.Logging)
	} else if a.ko.Spec.Logging != nil && b.ko.Spec.Logging != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.Logging.CloudWatch, b.ko.Spec.Logging.CloudWatch) {
			delta.Add("Spec.Logging.CloudWatch", a.ko.Spec.Logging.CloudWatch, b.ko.Spec.Logging.CloudWatch)
		} else if a.ko.Spec.Logging.CloudWatch != nil && b.ko.Spec.Logging.CloudWatch != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.Logging.CloudWatch.LogGroup, b.ko.Spec.Logging.CloudWatch.LogGroup) {
				delta.Add("Spec.Logging.CloudWatch.LogGroup", a.ko.Spec.Logging.CloudWatch.LogGroup, b.ko.Spec.Logging.CloudWatch.LogGroup)
			} else if a.ko.Spec.Logging.CloudWatch.LogGroup != nil && b.ko.Spec.Logging.CloudWatch.LogGroup != nil {
				if *a.ko.Spec.Logging.CloudWatch.LogGroup != *b.ko.Spec.Logging.CloudWatch.LogGroup {
					delta.Add("Spec.Logging.CloudWatch.LogGroup", a.ko.Spec.Logging.CloudWatch.LogGroup, b.ko.Spec.Logging.CloudWatch.LogGroup)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.Logging.CloudWatch.LogStream, b.ko.Spec.Logging.CloudWatch.LogStream) {
				delta.Add("Spec.Logging.CloudWatch.LogStream", a.ko.Spec.Logging.CloudWatch.LogStream, b.ko.Spec.Logging.CloudWatch.LogStream)
			} else if a.ko.Spec.Logging.CloudWatch.LogStream != nil && b.ko.Spec.Logging.CloudWatch.LogStream != nil {
				if *a.ko.Spec.Logging.CloudWatch.LogStream != *b.ko.Spec.Logging.CloudWatch.LogStream {
					delta.Add("Spec.Logging.CloudWatch.LogStream", a.ko.Spec.Logging.CloudWatch.LogStream, b.ko.Spec.Logging.CloudWatch.LogStream)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.Logging.Disabled, b.ko.Spec.Logging.Disabled) {
			delta.Add("Spec.Logging.Disabled", a.ko.Spec.Logging.Disabled, b.ko.Spec.Logging.Disabled)
		} else if a.ko.Spec.Logging.Disabled != nil && b.ko.Spec.Logging.Disabled != nil {
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	if len(a.ko.Spec.Resources) != len(b.ko.Spec.Resources) {
		delta.Add("Spec.Resources", a.ko.Spec.Resources, b.ko.Spec.Resources)
	} else if len(a.ko.Spec.Resources) > 0 {
		if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.Resources, b.ko.Spec.Resources) {
			delta.Add("Spec.Resources", a.ko.Spec.Resources, b.ko.Spec.Resources)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
