// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package microvm_image

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"
	"time"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	ackutil "github.com/aws-controllers-k8s/runtime/pkg/util"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/lambdamicrovms"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/lambdamicrovms/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/lambdamicrovms-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.MicrovmImage{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetMicrovmImageOutput
	resp, err = rm.sdkapi.GetMicrovmImage(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetMicrovmImage", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.LatestActiveImageVersion != nil {
		ko.Status.LatestActiveImageVersion = resp.LatestActiveImageVersion
	} else {
		ko.Status.LatestActiveImageVersion = nil
	}
	if resp.LatestFailedImageVersion != nil {
		ko.Status.LatestFailedImageVersion = resp.LatestFailedImageVersion
	} else {
		ko.Status.LatestFailedImageVersion = nil
	}
	if resp.Name != nil {
		ko.Spec.Name = resp.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.State != "" {
		ko.Status.State = aws.String(string(resp.State))
	} else {
		ko.Status.State = nil
	}
	if resp.Tags != nil {
		ko.Spec.Tags = aws.StringMap(resp.Tags)
	} else {
		ko.Spec.Tags = nil
	}
	if resp.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.ImageArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.ImageArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if err := rm.refreshSpecFromActiveVersion(ctx, ko); err != nil {
		return nil, err
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return (r.ko.Status.ACKResourceMetadata == nil || r.ko.Status.ACKResourceMetadata.ARN == nil)

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetMicrovmImageInput, error) {
	res := &svcsdk.GetMicrovmImageInput{}

	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.ImageIdentifier = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateMicrovmImageOutput
	_ = resp
	resp, err = rm.sdkapi.CreateMicrovmImage(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateMicrovmImage", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.AdditionalOsCapabilities != nil {
		f0 := []*string{}
		for _, f0iter := range resp.AdditionalOsCapabilities {
			var f0elem *string
			f0elem = aws.String(string(f0iter))
			f0 = append(f0, f0elem)
		}
		ko.Spec.AdditionalOsCapabilities = f0
	} else {
		ko.Spec.AdditionalOsCapabilities = nil
	}
	if resp.BaseImageArn != nil {
		ko.Spec.BaseImageARN = resp.BaseImageArn
	} else {
		ko.Spec.BaseImageARN = nil
	}
	if resp.BuildRoleArn != nil {
		ko.Spec.BuildRoleARN = resp.BuildRoleArn
	} else {
		ko.Spec.BuildRoleARN = nil
	}
	if resp.CodeArtifact != nil {
		f3 := &svcapitypes.CodeArtifact{}
		switch resp.CodeArtifact.(type) {
		case *svcsdktypes.CodeArtifactMemberUri:
			f3f0 := resp.CodeArtifact.(*svcsdktypes.CodeArtifactMemberUri)
			if f3f0 != nil {
				f3.URI = &f3f0.Value
			}
		}
		ko.Spec.CodeArtifact = f3
	} else {
		ko.Spec.CodeArtifact = nil
	}
	if resp.CpuConfigurations != nil {
		f4 := []*svcapitypes.CPUConfiguration{}
		for _, f4iter := range resp.CpuConfigurations {
			f4elem := &svcapitypes.CPUConfiguration{}
			if f4iter.Architecture != "" {
				f4elem.Architecture = aws.String(string(f4iter.Architecture))
			}
			f4 = append(f4, f4elem)
		}
		ko.Spec.CPUConfigurations = f4
	} else {
		ko.Spec.CPUConfigurations = nil
	}
	if resp.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.EgressNetworkConnectors != nil {
		ko.Spec.EgressNetworkConnectors = aws.StringSlice(resp.EgressNetworkConnectors)
	} else {
		ko.Spec.EgressNetworkConnectors = nil
	}
	if resp.EnvironmentVariables != nil {
		ko.Spec.EnvironmentVariables = aws.StringMap(resp.EnvironmentVariables)
	} else {
		ko.Spec.EnvironmentVariables = nil
	}
	if resp.Hooks != nil {
		f9 := &svcapitypes.Hooks{}
		if resp.Hooks.MicrovmHooks != nil {
			f9f0 := &svcapitypes.MicrovmHooks{}
			if resp.Hooks.MicrovmHooks.Resume != "" {
				f9f0.Resume = aws.String(string(resp.Hooks.MicrovmHooks.Resume))
			}
			if resp.Hooks.MicrovmHooks.ResumeTimeoutInSeconds != nil {
				resumeTimeoutInSecondsCopy := int64(*resp.Hooks.MicrovmHooks.ResumeTimeoutInSeconds)
				f9f0.ResumeTimeoutInSeconds = &resumeTimeoutInSecondsCopy
			}
			if resp.Hooks.MicrovmHooks.Run != "" {
				f9f0.Run = aws.String(string(resp.Hooks.MicrovmHooks.Run))
			}
			if resp.Hooks.MicrovmHooks.RunTimeoutInSeconds != nil {
				runTimeoutInSecondsCopy := int64(*resp.Hooks.MicrovmHooks.RunTimeoutInSeconds)
				f9f0.RunTimeoutInSeconds = &runTimeoutInSecondsCopy
			}
			if resp.Hooks.MicrovmHooks.Suspend != "" {
				f9f0.Suspend = aws.String(string(resp.Hooks.MicrovmHooks.Suspend))
			}
			if resp.Hooks.MicrovmHooks.SuspendTimeoutInSeconds != nil {
				suspendTimeoutInSecondsCopy := int64(*resp.Hooks.MicrovmHooks.SuspendTimeoutInSeconds)
				f9f0.SuspendTimeoutInSeconds = &suspendTimeoutInSecondsCopy
			}
			if resp.Hooks.MicrovmHooks.Terminate != "" {
				f9f0.Terminate = aws.String(string(resp.Hooks.MicrovmHooks.Terminate))
			}
			if resp.Hooks.MicrovmHooks.TerminateTimeoutInSeconds != nil {
				terminateTimeoutInSecondsCopy := int64(*resp.Hooks.MicrovmHooks.TerminateTimeoutInSeconds)
				f9f0.TerminateTimeoutInSeconds = &terminateTimeoutInSecondsCopy
			}
			f9.MicrovmHooks = f9f0
		}
		if resp.Hooks.MicrovmImageHooks != nil {
			f9f1 := &svcapitypes.MicrovmImageHooks{}
			if resp.Hooks.MicrovmImageHooks.Ready != "" {
				f9f1.Ready = aws.String(string(resp.Hooks.MicrovmImageHooks.Ready))
			}
			if resp.Hooks.MicrovmImageHooks.ReadyTimeoutInSeconds != nil {
				readyTimeoutInSecondsCopy := int64(*resp.Hooks.MicrovmImageHooks.ReadyTimeoutInSeconds)
				f9f1.ReadyTimeoutInSeconds = &readyTimeoutInSecondsCopy
			}
			if resp.Hooks.MicrovmImageHooks.Validate != "" {
				f9f1.Validate = aws.String(string(resp.Hooks.MicrovmImageHooks.Validate))
			}
			if resp.Hooks.MicrovmImageHooks.ValidateTimeoutInSeconds != nil {
				validateTimeoutInSecondsCopy := int64(*resp.Hooks.MicrovmImageHooks.ValidateTimeoutInSeconds)
				f9f1.ValidateTimeoutInSeconds = &validateTimeoutInSecondsCopy
			}
			f9.MicrovmImageHooks = f9f1
		}
		if resp.Hooks.Port != nil {
			portCopy := int64(*resp.Hooks.Port)
			f9.Port = &portCopy
		}
		ko.Spec.Hooks = f9
	} else {
		ko.Spec.Hooks = nil
	}
	if resp.ImageVersion != nil {
		ko.Status.ImageVersion = resp.ImageVersion
	} else {
		ko.Status.ImageVersion = nil
	}
	if resp.LatestActiveImageVersion != nil {
		ko.Status.LatestActiveImageVersion = resp.LatestActiveImageVersion
	} else {
		ko.Status.LatestActiveImageVersion = nil
	}
	if resp.LatestFailedImageVersion != nil {
		ko.Status.LatestFailedImageVersion = resp.LatestFailedImageVersion
	} else {
		ko.Status.LatestFailedImageVersion = nil
	}
	if resp.Logging != nil {
		f13 := &svcapitypes.Logging{}
		switch resp.Logging.(type) {
		case *svcsdktypes.LoggingMemberCloudWatch:
			f13f0 := resp.Logging.(*svcsdktypes.LoggingMemberCloudWatch)
			if f13f0 != nil {
				f13f0f0 := &svcapitypes.CloudWatchLogging{}
				if f13f0.Value.LogGroup != nil {
					f13f0f0.LogGroup = f13f0.Value.LogGroup
				}
				if f13f0.Value.LogStream != nil {
					f13f0f0.LogStream = f13f0.Value.LogStream
				}
				f13.CloudWatch = f13f0f0
			}
		case *svcsdktypes.LoggingMemberDisabled:
			f13f1 := resp.Logging.(*svcsdktypes.LoggingMemberDisabled)
			if f13f1 != nil {
				f13f1f1 := map[string]*string{}
				f13.Disabled = f13f1f1
			}
		}
		ko.Spec.Logging = f13
	} else {
		ko.Spec.Logging = nil
	}
	if resp.Name != nil {
		ko.Spec.Name = resp.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.Resources != nil {
		f15 := []*svcapitypes.Resources{}
		for _, f15iter := range resp.Resources {
			f15elem := &svcapitypes.Resources{}
			if f15iter.MinimumMemoryInMiB != nil {
				minimumMemoryInMiBCopy := int64(*f15iter.MinimumMemoryInMiB)
				f15elem.MinimumMemoryInMiB = &minimumMemoryInMiBCopy
			}
			f15 = append(f15, f15elem)
		}
		ko.Spec.Resources = f15
	} else {
		ko.Spec.Resources = nil
	}
	if resp.State != "" {
		ko.Status.State = aws.String(string(resp.State))
	} else {
		ko.Status.State = nil
	}
	if resp.Tags != nil {
		ko.Spec.Tags = aws.StringMap(resp.Tags)
	} else {
		ko.Spec.Tags = nil
	}
	if resp.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.ImageArn != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.ImageArn)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	// Persist the sanitized base image version the API accepts into Spec (and
	// the full resolved value into Status) straight from the create response, so
	// it lands in etcd immediately and later reconciles see no spurious delta.
	ko.Status.ResolvedBaseImageVersion = resp.BaseImageVersion
	ko.Spec.BaseImageVersion = sanitizeBaseImageVersion(resp.BaseImageVersion)

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateMicrovmImageInput, error) {
	res := &svcsdk.CreateMicrovmImageInput{}

	if r.ko.Spec.AdditionalOsCapabilities != nil {
		f0 := []svcsdktypes.Capability{}
		for _, f0iter := range r.ko.Spec.AdditionalOsCapabilities {
			var f0elem string
			f0elem = string(*f0iter)
			f0 = append(f0, svcsdktypes.Capability(f0elem))
		}
		res.AdditionalOsCapabilities = f0
	}
	if r.ko.Spec.BaseImageARN != nil {
		res.BaseImageArn = r.ko.Spec.BaseImageARN
	}
	if r.ko.Spec.BaseImageVersion != nil {
		res.BaseImageVersion = r.ko.Spec.BaseImageVersion
	}
	if r.ko.Spec.BuildRoleARN != nil {
		res.BuildRoleArn = r.ko.Spec.BuildRoleARN
	}
	if r.ko.Spec.CodeArtifact != nil {
		var f5 svcsdktypes.CodeArtifact
		isInterfaceSet := false
		if r.ko.Spec.CodeArtifact.URI != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for Uri"))
			}
			f5f0Parent := &svcsdktypes.CodeArtifactMemberUri{}
			f5f0Parent.Value = *r.ko.Spec.CodeArtifact.URI
			f5 = f5f0Parent
			isInterfaceSet = true
		}
		res.CodeArtifact = f5
	}
	if r.ko.Spec.CPUConfigurations != nil {
		f6 := []svcsdktypes.CpuConfiguration{}
		for _, f6iter := range r.ko.Spec.CPUConfigurations {
			f6elem := &svcsdktypes.CpuConfiguration{}
			if f6iter.Architecture != nil {
				f6elem.Architecture = svcsdktypes.Architecture(*f6iter.Architecture)
			}
			f6 = append(f6, *f6elem)
		}
		res.CpuConfigurations = f6
	}
	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.EgressNetworkConnectors != nil {
		res.EgressNetworkConnectors = aws.ToStringSlice(r.ko.Spec.EgressNetworkConnectors)
	}
	if r.ko.Spec.EnvironmentVariables != nil {
		res.EnvironmentVariables = aws.ToStringMap(r.ko.Spec.EnvironmentVariables)
	}
	if r.ko.Spec.Hooks != nil {
		f10 := &svcsdktypes.Hooks{}
		if r.ko.Spec.Hooks.MicrovmHooks != nil {
			f10f0 := &svcsdktypes.MicrovmHooks{}
			if r.ko.Spec.Hooks.MicrovmHooks.Resume != nil {
				f10f0.Resume = svcsdktypes.HookState(*r.ko.Spec.Hooks.MicrovmHooks.Resume)
			}
			if r.ko.Spec.Hooks.MicrovmHooks.ResumeTimeoutInSeconds != nil {
				resumeTimeoutInSecondsCopy0 := *r.ko.Spec.Hooks.MicrovmHooks.ResumeTimeoutInSeconds
				if resumeTimeoutInSecondsCopy0 > math.MaxInt32 || resumeTimeoutInSecondsCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field resumeTimeoutInSeconds is of type int32")
				}
				resumeTimeoutInSecondsCopy := int32(resumeTimeoutInSecondsCopy0)
				f10f0.ResumeTimeoutInSeconds = &resumeTimeoutInSecondsCopy
			}
			if r.ko.Spec.Hooks.MicrovmHooks.Run != nil {
				f10f0.Run = svcsdktypes.HookState(*r.ko.Spec.Hooks.MicrovmHooks.Run)
			}
			if r.ko.Spec.Hooks.MicrovmHooks.RunTimeoutInSeconds != nil {
				runTimeoutInSecondsCopy0 := *r.ko.Spec.Hooks.MicrovmHooks.RunTimeoutInSeconds
				if runTimeoutInSecondsCopy0 > math.MaxInt32 || runTimeoutInSecondsCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field runTimeoutInSeconds is of type int32")
				}
				runTimeoutInSecondsCopy := int32(runTimeoutInSecondsCopy0)
				f10f0.RunTimeoutInSeconds = &runTimeoutInSecondsCopy
			}
			if r.ko.Spec.Hooks.MicrovmHooks.Suspend != nil {
				f10f0.Suspend = svcsdktypes.HookState(*r.ko.Spec.Hooks.MicrovmHooks.Suspend)
			}
			if r.ko.Spec.Hooks.MicrovmHooks.SuspendTimeoutInSeconds != nil {
				suspendTimeoutInSecondsCopy0 := *r.ko.Spec.Hooks.MicrovmHooks.SuspendTimeoutInSeconds
				if suspendTimeoutInSecondsCopy0 > math.MaxInt32 || suspendTimeoutInSecondsCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field suspendTimeoutInSeconds is of type int32")
				}
				suspendTimeoutInSecondsCopy := int32(suspendTimeoutInSecondsCopy0)
				f10f0.SuspendTimeoutInSeconds = &suspendTimeoutInSecondsCopy
			}
			if r.ko.Spec.Hooks.MicrovmHooks.Terminate != nil {
				f10f0.Terminate = svcsdktypes.HookState(*r.ko.Spec.Hooks.MicrovmHooks.Terminate)
			}
			if r.ko.Spec.Hooks.MicrovmHooks.TerminateTimeoutInSeconds != nil {
				terminateTimeoutInSecondsCopy0 := *r.ko.Spec.Hooks.MicrovmHooks.TerminateTimeoutInSeconds
				if terminateTimeoutInSecondsCopy0 > math.MaxInt32 || terminateTimeoutInSecondsCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field terminateTimeoutInSeconds is of type int32")
				}
				terminateTimeoutInSecondsCopy := int32(terminateTimeoutInSecondsCopy0)
				f10f0.TerminateTimeoutInSeconds = &terminateTimeoutInSecondsCopy
			}
			f10.MicrovmHooks = f10f0
		}
		if r.ko.Spec.Hooks.MicrovmImageHooks != nil {
			f10f1 := &svcsdktypes.MicrovmImageHooks{}
			if r.ko.Spec.Hooks.MicrovmImageHooks.Ready != nil {
				f10f1.Ready = svcsdktypes.HookState(*r.ko.Spec.Hooks.MicrovmImageHooks.Ready)
			}
			if r.ko.Spec.Hooks.MicrovmImageHooks.ReadyTimeoutInSeconds != nil {
				readyTimeoutInSecondsCopy0 := *r.ko.Spec.Hooks.MicrovmImageHooks.ReadyTimeoutInSeconds
				if readyTimeoutInSecondsCopy0 > math.MaxInt32 || readyTimeoutInSecondsCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field readyTimeoutInSeconds is of type int32")
				}
				readyTimeoutInSecondsCopy := int32(readyTimeoutInSecondsCopy0)
				f10f1.ReadyTimeoutInSeconds = &readyTimeoutInSecondsCopy
			}
			if r.ko.Spec.Hooks.MicrovmImageHooks.Validate != nil {
				f10f1.Validate = svcsdktypes.HookState(*r.ko.Spec.Hooks.MicrovmImageHooks.Validate)
			}
			if r.ko.Spec.Hooks.MicrovmImageHooks.ValidateTimeoutInSeconds != nil {
				validateTimeoutInSecondsCopy0 := *r.ko.Spec.Hooks.MicrovmImageHooks.ValidateTimeoutInSeconds
				if validateTimeoutInSecondsCopy0 > math.MaxInt32 || validateTimeoutInSecondsCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field validateTimeoutInSeconds is of type int32")
				}
				validateTimeoutInSecondsCopy := int32(validateTimeoutInSecondsCopy0)
				f10f1.ValidateTimeoutInSeconds = &validateTimeoutInSecondsCopy
			}
			f10.MicrovmImageHooks = f10f1
		}
		if r.ko.Spec.Hooks.Port != nil {
			portCopy0 := *r.ko.Spec.Hooks.Port
			if portCopy0 > math.MaxInt32 || portCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field port is of type int32")
			}
			portCopy := int32(portCopy0)
			f10.Port = &portCopy
		}
		res.Hooks = f10
	}
	if r.ko.Spec.Logging != nil {
		var f11 svcsdktypes.Logging
		isInterfaceSet := false
		if r.ko.Spec.Logging.CloudWatch != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for CloudWatch"))
			}
			f11f0Parent := &svcsdktypes.LoggingMemberCloudWatch{}
			f11f0 := &svcsdktypes.CloudWatchLogging{}
			if r.ko.Spec.Logging.CloudWatch.LogGroup != nil {
				f11f0.LogGroup = r.ko.Spec.Logging.CloudWatch.LogGroup
			}
			if r.ko.Spec.Logging.CloudWatch.LogStream != nil {
				f11f0.LogStream = r.ko.Spec.Logging.CloudWatch.LogStream
			}
			f11f0Parent.Value = *f11f0
			f11 = f11f0Parent
			isInterfaceSet = true
		}
		if r.ko.Spec.Logging.Disabled != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for Disabled"))
			}
			f11f1Parent := &svcsdktypes.LoggingMemberDisabled{}
			f11f1 := &svcsdktypes.LoggingDisabled{}
			f11f1Parent.Value = *f11f1
			f11 = f11f1Parent
			isInterfaceSet = true
		}
		res.Logging = f11
	}
	if r.ko.Spec.Name != nil {
		res.Name = r.ko.Spec.Name
	}
	if r.ko.Spec.Resources != nil {
		f13 := []svcsdktypes.Resources{}
		for _, f13iter := range r.ko.Spec.Resources {
			f13elem := &svcsdktypes.Resources{}
			if f13iter.MinimumMemoryInMiB != nil {
				minimumMemoryInMiBCopy0 := *f13iter.MinimumMemoryInMiB
				if minimumMemoryInMiBCopy0 > math.MaxInt32 || minimumMemoryInMiBCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field minimumMemoryInMiB is of type int32")
				}
				minimumMemoryInMiBCopy := int32(minimumMemoryInMiBCopy0)
				f13elem.MinimumMemoryInMiB = &minimumMemoryInMiBCopy
			}
			f13 = append(f13, *f13elem)
		}
		res.Resources = f13
	}
	if r.ko.Spec.Tags != nil {
		res.Tags = aws.ToStringMap(r.ko.Spec.Tags)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (updated *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkUpdate")
	defer func() {
		exit(err)
	}()
	if delta.DifferentAt("Spec.Tags") {
		if err := rm.syncTags(ctx, desired, latest); err != nil {
			return nil, err
		}
	}
	if !delta.DifferentExcept("Spec.Tags") {
		// Tags-only change: already synced above; skip UpdateMicrovmImage
		// (it triggers a full rebuild).
		return desired, nil
	}

	if latest.ko.Status.State != nil {
		if !ackutil.InStrings(*latest.ko.Status.State, []string{"CREATED", "UPDATED", "CREATE_FAILED", "UPDATE_FAILED"}) {
			return nil, ackrequeue.NeededAfter(
				fmt.Errorf("resource is in %s state, cannot be updated",
					*latest.ko.Status.State),
				time.Duration(30)*time.Second,
			)
		}
	}

	input, err := rm.newUpdateRequestPayload(ctx, desired, delta)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.UpdateMicrovmImageOutput
	_ = resp
	resp, err = rm.sdkapi.UpdateMicrovmImage(ctx, input)
	rm.metrics.RecordAPICall("UPDATE", "UpdateMicrovmImage", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.AdditionalOsCapabilities != nil {
		f0 := []*string{}
		for _, f0iter := range resp.AdditionalOsCapabilities {
			var f0elem *string
			f0elem = aws.String(string(f0iter))
			f0 = append(f0, f0elem)
		}
		ko.Spec.AdditionalOsCapabilities = f0
	} else {
		ko.Spec.AdditionalOsCapabilities = nil
	}
	if resp.BaseImageArn != nil {
		ko.Spec.BaseImageARN = resp.BaseImageArn
	} else {
		ko.Spec.BaseImageARN = nil
	}
	if resp.BuildRoleArn != nil {
		ko.Spec.BuildRoleARN = resp.BuildRoleArn
	} else {
		ko.Spec.BuildRoleARN = nil
	}
	if resp.CodeArtifact != nil {
		f3 := &svcapitypes.CodeArtifact{}
		switch resp.CodeArtifact.(type) {
		case *svcsdktypes.CodeArtifactMemberUri:
			f3f0 := resp.CodeArtifact.(*svcsdktypes.CodeArtifactMemberUri)
			if f3f0 != nil {
				f3.URI = &f3f0.Value
			}
		}
		ko.Spec.CodeArtifact = f3
	} else {
		ko.Spec.CodeArtifact = nil
	}
	if resp.CpuConfigurations != nil {
		f4 := []*svcapitypes.CPUConfiguration{}
		for _, f4iter := range resp.CpuConfigurations {
			f4elem := &svcapitypes.CPUConfiguration{}
			if f4iter.Architecture != "" {
				f4elem.Architecture = aws.String(string(f4iter.Architecture))
			}
			f4 = append(f4, f4elem)
		}
		ko.Spec.CPUConfigurations = f4
	} else {
		ko.Spec.CPUConfigurations = nil
	}
	if resp.CreatedAt != nil {
		ko.Status.CreatedAt = &metav1.Time{*resp.CreatedAt}
	} else {
		ko.Status.CreatedAt = nil
	}
	if resp.Description != nil {
		ko.Spec.Description = resp.Description
	} else {
		ko.Spec.Description = nil
	}
	if resp.EgressNetworkConnectors != nil {
		ko.Spec.EgressNetworkConnectors = aws.StringSlice(resp.EgressNetworkConnectors)
	} else {
		ko.Spec.EgressNetworkConnectors = nil
	}
	if resp.EnvironmentVariables != nil {
		ko.Spec.EnvironmentVariables = aws.StringMap(resp.EnvironmentVariables)
	} else {
		ko.Spec.EnvironmentVariables = nil
	}
	if resp.Hooks != nil {
		f9 := &svcapitypes.Hooks{}
		if resp.Hooks.MicrovmHooks != nil {
			f9f0 := &svcapitypes.MicrovmHooks{}
			if resp.Hooks.MicrovmHooks.Resume != "" {
				f9f0.Resume = aws.String(string(resp.Hooks.MicrovmHooks.Resume))
			}
			if resp.Hooks.MicrovmHooks.ResumeTimeoutInSeconds != nil {
				resumeTimeoutInSecondsCopy := int64(*resp.Hooks.MicrovmHooks.ResumeTimeoutInSeconds)
				f9f0.ResumeTimeoutInSeconds = &resumeTimeoutInSecondsCopy
			}
			if resp.Hooks.MicrovmHooks.Run != "" {
				f9f0.Run = aws.String(string(resp.Hooks.MicrovmHooks.Run))
			}
			if resp.Hooks.MicrovmHooks.RunTimeoutInSeconds != nil {
				runTimeoutInSecondsCopy := int64(*resp.Hooks.MicrovmHooks.RunTimeoutInSeconds)
				f9f0.RunTimeoutInSeconds = &runTimeoutInSecondsCopy
			}
			if resp.Hooks.MicrovmHooks.Suspend != "" {
				f9f0.Suspend = aws.String(string(resp.Hooks.MicrovmHooks.Suspend))
			}
			if resp.Hooks.MicrovmHooks.SuspendTimeoutInSeconds != nil {
				suspendTimeoutInSecondsCopy := int64(*resp.Hooks.MicrovmHooks.SuspendTimeoutInSeconds)
				f9f0.SuspendTimeoutInSeconds = &suspendTimeoutInSecondsCopy
			}
			if resp.Hooks.MicrovmHooks.Terminate != "" {
				f9f0.Terminate = aws.String(string(resp.Hooks.MicrovmHooks.Terminate))
			}
			if resp.Hooks.MicrovmHooks.TerminateTimeoutInSeconds != nil {
				terminateTimeoutInSecondsCopy := int64(*resp.Hooks.MicrovmHooks.TerminateTimeoutInSeconds)
				f9f0.TerminateTimeoutInSeconds = &terminateTimeoutInSecondsCopy
			}
			f9.MicrovmHooks = f9f0
		}
		if resp.Hooks.MicrovmImageHooks != nil {
			f9f1 := &svcapitypes.MicrovmImageHooks{}
			if resp.Hooks.MicrovmImageHooks.Ready != "" {
				f9f1.Ready = aws.String(string(resp.Hooks.MicrovmImageHooks.Ready))
			}
			if resp.Hooks.MicrovmImageHooks.ReadyTimeoutInSeconds != nil {
				readyTimeoutInSecondsCopy := int64(*resp.Hooks.MicrovmImageHooks.ReadyTimeoutInSeconds)
				f9f1.ReadyTimeoutInSeconds = &readyTimeoutInSecondsCopy
			}
			if resp.Hooks.MicrovmImageHooks.Validate != "" {
				f9f1.Validate = aws.String(string(resp.Hooks.MicrovmImageHooks.Validate))
			}
			if resp.Hooks.MicrovmImageHooks.ValidateTimeoutInSeconds != nil {
				validateTimeoutInSecondsCopy := int64(*resp.Hooks.MicrovmImageHooks.ValidateTimeoutInSeconds)
				f9f1.ValidateTimeoutInSeconds = &validateTimeoutInSecondsCopy
			}
			f9.MicrovmImageHooks = f9f1
		}
		if resp.Hooks.Port != nil {
			portCopy := int64(*resp.Hooks.Port)
			f9.Port = &portCopy
		}
		ko.Spec.Hooks = f9
	} else {
		ko.Spec.Hooks = nil
	}
	if resp.ImageVersion != nil {
		ko.Status.ImageVersion = resp.ImageVersion
	} else {
		ko.Status.ImageVersion = nil
	}
	if resp.LatestActiveImageVersion != nil {
		ko.Status.LatestActiveImageVersion = resp.LatestActiveImageVersion
	} else {
		ko.Status.LatestActiveImageVersion = nil
	}
	if resp.LatestFailedImageVersion != nil {
		ko.Status.LatestFailedImageVersion = resp.LatestFailedImageVersion
	} else {
		ko.Status.LatestFailedImageVersion = nil
	}
	if resp.Logging != nil {
		f14 := &svcapitypes.Logging{}
		switch resp.Logging.(type) {
		case *svcsdktypes.LoggingMemberCloudWatch:
			f14f0 := resp.Logging.(*svcsdktypes.LoggingMemberCloudWatch)
			if f14f0 != nil {
				f14f0f0 := &svcapitypes.CloudWatchLogging{}
				if f14f0.Value.LogGroup != nil {
					f14f0f0.LogGroup = f14f0.Value.LogGroup
				}
				if f14f0.Value.LogStream != nil {
					f14f0f0.LogStream = f14f0.Value.LogStream
				}
				f14.CloudWatch = f14f0f0
			}
		case *svcsdktypes.LoggingMemberDisabled:
			f14f1 := resp.Logging.(*svcsdktypes.LoggingMemberDisabled)
			if f14f1 != nil {
				f14f1f1 := map[string]*string{}
				f14.Disabled = f14f1f1
			}
		}
		ko.Spec.Logging = f14
	} else {
		ko.Spec.Logging = nil
	}
	if resp.Name != nil {
		ko.Spec.Name = resp.Name
	} else {
		ko.Spec.Name = nil
	}
	if resp.Resources != nil {
		f16 := []*svcapitypes.Resources{}
		for _, f16iter := range resp.Resources {
			f16elem := &svcapitypes.Resources{}
			if f16iter.MinimumMemoryInMiB != nil {
				minimumMemoryInMiBCopy := int64(*f16iter.MinimumMemoryInMiB)
				f16elem.MinimumMemoryInMiB = &minimumMemoryInMiBCopy
			}
			f16 = append(f16, f16elem)
		}
		ko.Spec.Resources = f16
	} else {
		ko.Spec.Resources = nil
	}
	if resp.State != "" {
		ko.Status.State = aws.String(string(resp.State))
	} else {
		ko.Status.State = nil
	}
	if resp.UpdatedAt != nil {
		ko.Status.UpdatedAt = &metav1.Time{*resp.UpdatedAt}
	} else {
		ko.Status.UpdatedAt = nil
	}

	rm.setStatusDefaults(ko)
	// Keep the base image version fresh straight from the update response: the
	// sanitized value the API accepts in Spec, the full resolved value in Status.
	ko.Status.ResolvedBaseImageVersion = resp.BaseImageVersion
	ko.Spec.BaseImageVersion = sanitizeBaseImageVersion(resp.BaseImageVersion)

	return &resource{ko}, nil
}

// newUpdateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Update API call for the resource
func (rm *resourceManager) newUpdateRequestPayload(
	ctx context.Context,
	r *resource,
	delta *ackcompare.Delta,
) (*svcsdk.UpdateMicrovmImageInput, error) {
	res := &svcsdk.UpdateMicrovmImageInput{}

	if r.ko.Spec.AdditionalOsCapabilities != nil {
		f0 := []svcsdktypes.Capability{}
		for _, f0iter := range r.ko.Spec.AdditionalOsCapabilities {
			var f0elem string
			f0elem = string(*f0iter)
			f0 = append(f0, svcsdktypes.Capability(f0elem))
		}
		res.AdditionalOsCapabilities = f0
	}
	if r.ko.Spec.BaseImageARN != nil {
		res.BaseImageArn = r.ko.Spec.BaseImageARN
	}
	if r.ko.Spec.BaseImageVersion != nil {
		res.BaseImageVersion = r.ko.Spec.BaseImageVersion
	}
	if r.ko.Spec.BuildRoleARN != nil {
		res.BuildRoleArn = r.ko.Spec.BuildRoleARN
	}
	if r.ko.Spec.CodeArtifact != nil {
		var f5 svcsdktypes.CodeArtifact
		isInterfaceSet := false
		if r.ko.Spec.CodeArtifact.URI != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for Uri"))
			}
			f5f0Parent := &svcsdktypes.CodeArtifactMemberUri{}
			f5f0Parent.Value = *r.ko.Spec.CodeArtifact.URI
			f5 = f5f0Parent
			isInterfaceSet = true
		}
		res.CodeArtifact = f5
	}
	if r.ko.Spec.CPUConfigurations != nil {
		f6 := []svcsdktypes.CpuConfiguration{}
		for _, f6iter := range r.ko.Spec.CPUConfigurations {
			f6elem := &svcsdktypes.CpuConfiguration{}
			if f6iter.Architecture != nil {
				f6elem.Architecture = svcsdktypes.Architecture(*f6iter.Architecture)
			}
			f6 = append(f6, *f6elem)
		}
		res.CpuConfigurations = f6
	}
	if r.ko.Spec.Description != nil {
		res.Description = r.ko.Spec.Description
	}
	if r.ko.Spec.EgressNetworkConnectors != nil {
		res.EgressNetworkConnectors = aws.ToStringSlice(r.ko.Spec.EgressNetworkConnectors)
	}
	if r.ko.Spec.EnvironmentVariables != nil {
		res.EnvironmentVariables = aws.ToStringMap(r.ko.Spec.EnvironmentVariables)
	}
	if r.ko.Spec.Hooks != nil {
		f10 := &svcsdktypes.Hooks{}
		if r.ko.Spec.Hooks.MicrovmHooks != nil {
			f10f0 := &svcsdktypes.MicrovmHooks{}
			if r.ko.Spec.Hooks.MicrovmHooks.Resume != nil {
				f10f0.Resume = svcsdktypes.HookState(*r.ko.Spec.Hooks.MicrovmHooks.Resume)
			}
			if r.ko.Spec.Hooks.MicrovmHooks.ResumeTimeoutInSeconds != nil {
				resumeTimeoutInSecondsCopy0 := *r.ko.Spec.Hooks.MicrovmHooks.ResumeTimeoutInSeconds
				if resumeTimeoutInSecondsCopy0 > math.MaxInt32 || resumeTimeoutInSecondsCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field resumeTimeoutInSeconds is of type int32")
				}
				resumeTimeoutInSecondsCopy := int32(resumeTimeoutInSecondsCopy0)
				f10f0.ResumeTimeoutInSeconds = &resumeTimeoutInSecondsCopy
			}
			if r.ko.Spec.Hooks.MicrovmHooks.Run != nil {
				f10f0.Run = svcsdktypes.HookState(*r.ko.Spec.Hooks.MicrovmHooks.Run)
			}
			if r.ko.Spec.Hooks.MicrovmHooks.RunTimeoutInSeconds != nil {
				runTimeoutInSecondsCopy0 := *r.ko.Spec.Hooks.MicrovmHooks.RunTimeoutInSeconds
				if runTimeoutInSecondsCopy0 > math.MaxInt32 || runTimeoutInSecondsCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field runTimeoutInSeconds is of type int32")
				}
				runTimeoutInSecondsCopy := int32(runTimeoutInSecondsCopy0)
				f10f0.RunTimeoutInSeconds = &runTimeoutInSecondsCopy
			}
			if r.ko.Spec.Hooks.MicrovmHooks.Suspend != nil {
				f10f0.Suspend = svcsdktypes.HookState(*r.ko.Spec.Hooks.MicrovmHooks.Suspend)
			}
			if r.ko.Spec.Hooks.MicrovmHooks.SuspendTimeoutInSeconds != nil {
				suspendTimeoutInSecondsCopy0 := *r.ko.Spec.Hooks.MicrovmHooks.SuspendTimeoutInSeconds
				if suspendTimeoutInSecondsCopy0 > math.MaxInt32 || suspendTimeoutInSecondsCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field suspendTimeoutInSeconds is of type int32")
				}
				suspendTimeoutInSecondsCopy := int32(suspendTimeoutInSecondsCopy0)
				f10f0.SuspendTimeoutInSeconds = &suspendTimeoutInSecondsCopy
			}
			if r.ko.Spec.Hooks.MicrovmHooks.Terminate != nil {
				f10f0.Terminate = svcsdktypes.HookState(*r.ko.Spec.Hooks.MicrovmHooks.Terminate)
			}
			if r.ko.Spec.Hooks.MicrovmHooks.TerminateTimeoutInSeconds != nil {
				terminateTimeoutInSecondsCopy0 := *r.ko.Spec.Hooks.MicrovmHooks.TerminateTimeoutInSeconds
				if terminateTimeoutInSecondsCopy0 > math.MaxInt32 || terminateTimeoutInSecondsCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field terminateTimeoutInSeconds is of type int32")
				}
				terminateTimeoutInSecondsCopy := int32(terminateTimeoutInSecondsCopy0)
				f10f0.TerminateTimeoutInSeconds = &terminateTimeoutInSecondsCopy
			}
			f10.MicrovmHooks = f10f0
		}
		if r.ko.Spec.Hooks.MicrovmImageHooks != nil {
			f10f1 := &svcsdktypes.MicrovmImageHooks{}
			if r.ko.Spec.Hooks.MicrovmImageHooks.Ready != nil {
				f10f1.Ready = svcsdktypes.HookState(*r.ko.Spec.Hooks.MicrovmImageHooks.Ready)
			}
			if r.ko.Spec.Hooks.MicrovmImageHooks.ReadyTimeoutInSeconds != nil {
				readyTimeoutInSecondsCopy0 := *r.ko.Spec.Hooks.MicrovmImageHooks.ReadyTimeoutInSeconds
				if readyTimeoutInSecondsCopy0 > math.MaxInt32 || readyTimeoutInSecondsCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field readyTimeoutInSeconds is of type int32")
				}
				readyTimeoutInSecondsCopy := int32(readyTimeoutInSecondsCopy0)
				f10f1.ReadyTimeoutInSeconds = &readyTimeoutInSecondsCopy
			}
			if r.ko.Spec.Hooks.MicrovmImageHooks.Validate != nil {
				f10f1.Validate = svcsdktypes.HookState(*r.ko.Spec.Hooks.MicrovmImageHooks.Validate)
			}
			if r.ko.Spec.Hooks.MicrovmImageHooks.ValidateTimeoutInSeconds != nil {
				validateTimeoutInSecondsCopy0 := *r.ko.Spec.Hooks.MicrovmImageHooks.ValidateTimeoutInSeconds
				if validateTimeoutInSecondsCopy0 > math.MaxInt32 || validateTimeoutInSecondsCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field validateTimeoutInSeconds is of type int32")
				}
				validateTimeoutInSecondsCopy := int32(validateTimeoutInSecondsCopy0)
				f10f1.ValidateTimeoutInSeconds = &validateTimeoutInSecondsCopy
			}
			f10.MicrovmImageHooks = f10f1
		}
		if r.ko.Spec.Hooks.Port != nil {
			portCopy0 := *r.ko.Spec.Hooks.Port
			if portCopy0 > math.MaxInt32 || portCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field port is of type int32")
			}
			portCopy := int32(portCopy0)
			f10.Port = &portCopy
		}
		res.Hooks = f10
	}
	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.ImageIdentifier = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}
	if r.ko.Spec.Logging != nil {
		var f12 svcsdktypes.Logging
		isInterfaceSet := false
		if r.ko.Spec.Logging.CloudWatch != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for CloudWatch"))
			}
			f12f0Parent := &svcsdktypes.LoggingMemberCloudWatch{}
			f12f0 := &svcsdktypes.CloudWatchLogging{}
			if r.ko.Spec.Logging.CloudWatch.LogGroup != nil {
				f12f0.LogGroup = r.ko.Spec.Logging.CloudWatch.LogGroup
			}
			if r.ko.Spec.Logging.CloudWatch.LogStream != nil {
				f12f0.LogStream = r.ko.Spec.Logging.CloudWatch.LogStream
			}
			f12f0Parent.Value = *f12f0
			f12 = f12f0Parent
			isInterfaceSet = true
		}
		if r.ko.Spec.Logging.Disabled != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for Disabled"))
			}
			f12f1Parent := &svcsdktypes.LoggingMemberDisabled{}
			f12f1 := &svcsdktypes.LoggingDisabled{}
			f12f1Parent.Value = *f12f1
			f12 = f12f1Parent
			isInterfaceSet = true
		}
		res.Logging = f12
	}
	if r.ko.Spec.Resources != nil {
		f13 := []svcsdktypes.Resources{}
		for _, f13iter := range r.ko.Spec.Resources {
			f13elem := &svcsdktypes.Resources{}
			if f13iter.MinimumMemoryInMiB != nil {
				minimumMemoryInMiBCopy0 := *f13iter.MinimumMemoryInMiB
				if minimumMemoryInMiBCopy0 > math.MaxInt32 || minimumMemoryInMiBCopy0 < math.MinInt32 {
					return nil, fmt.Errorf("error: field minimumMemoryInMiB is of type int32")
				}
				minimumMemoryInMiBCopy := int32(minimumMemoryInMiBCopy0)
				f13elem.MinimumMemoryInMiB = &minimumMemoryInMiBCopy
			}
			f13 = append(f13, *f13elem)
		}
		res.Resources = f13
	}

	return res, nil
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	if r.ko.Status.State != nil {
		if !ackutil.InStrings(*r.ko.Status.State, []string{"CREATED", "UPDATED", "CREATE_FAILED", "UPDATE_FAILED", "DELETE_FAILED"}) {
			return nil, ackrequeue.NeededAfter(
				fmt.Errorf("resource is in %s state, cannot be deleted",
					*r.ko.Status.State),
				time.Duration(30)*time.Second,
			)
		}
	}

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteMicrovmImageOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteMicrovmImage(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteMicrovmImage", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteMicrovmImageInput, error) {
	res := &svcsdk.DeleteMicrovmImageInput{}

	if r.ko.Status.ACKResourceMetadata != nil && r.ko.Status.ACKResourceMetadata.ARN != nil {
		res.ImageIdentifier = (*string)(r.ko.Status.ACKResourceMetadata.ARN)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.MicrovmImage,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ValidationException",
		"InvalidParameterValueException":
		return true
	default:
		return false
	}
}
