// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package microvm

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if len(a.ko.Spec.EgressNetworkConnectors) != len(b.ko.Spec.EgressNetworkConnectors) {
		delta.Add("Spec.EgressNetworkConnectors", a.ko.Spec.EgressNetworkConnectors, b.ko.Spec.EgressNetworkConnectors)
	} else if len(a.ko.Spec.EgressNetworkConnectors) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.EgressNetworkConnectors, b.ko.Spec.EgressNetworkConnectors) {
			delta.Add("Spec.EgressNetworkConnectors", a.ko.Spec.EgressNetworkConnectors, b.ko.Spec.EgressNetworkConnectors)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ExecutionRoleARN, b.ko.Spec.ExecutionRoleARN) {
		delta.Add("Spec.ExecutionRoleARN", a.ko.Spec.ExecutionRoleARN, b.ko.Spec.ExecutionRoleARN)
	} else if a.ko.Spec.ExecutionRoleARN != nil && b.ko.Spec.ExecutionRoleARN != nil {
		if *a.ko.Spec.ExecutionRoleARN != *b.ko.Spec.ExecutionRoleARN {
			delta.Add("Spec.ExecutionRoleARN", a.ko.Spec.ExecutionRoleARN, b.ko.Spec.ExecutionRoleARN)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.ExecutionRoleRef, b.ko.Spec.ExecutionRoleRef) {
		delta.Add("Spec.ExecutionRoleRef", a.ko.Spec.ExecutionRoleRef, b.ko.Spec.ExecutionRoleRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.IdlePolicy, b.ko.Spec.IdlePolicy) {
		delta.Add("Spec.IdlePolicy", a.ko.Spec.IdlePolicy, b.ko.Spec.IdlePolicy)
	} else if a.ko.Spec.IdlePolicy != nil && b.ko.Spec.IdlePolicy != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.IdlePolicy.AutoResumeEnabled, b.ko.Spec.IdlePolicy.AutoResumeEnabled) {
			delta.Add("Spec.IdlePolicy.AutoResumeEnabled", a.ko.Spec.IdlePolicy.AutoResumeEnabled, b.ko.Spec.IdlePolicy.AutoResumeEnabled)
		} else if a.ko.Spec.IdlePolicy.AutoResumeEnabled != nil && b.ko.Spec.IdlePolicy.AutoResumeEnabled != nil {
			if *a.ko.Spec.IdlePolicy.AutoResumeEnabled != *b.ko.Spec.IdlePolicy.AutoResumeEnabled {
				delta.Add("Spec.IdlePolicy.AutoResumeEnabled", a.ko.Spec.IdlePolicy.AutoResumeEnabled, b.ko.Spec.IdlePolicy.AutoResumeEnabled)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.IdlePolicy.MaxIdleDurationSeconds, b.ko.Spec.IdlePolicy.MaxIdleDurationSeconds) {
			delta.Add("Spec.IdlePolicy.MaxIdleDurationSeconds", a.ko.Spec.IdlePolicy.MaxIdleDurationSeconds, b.ko.Spec.IdlePolicy.MaxIdleDurationSeconds)
		} else if a.ko.Spec.IdlePolicy.MaxIdleDurationSeconds != nil && b.ko.Spec.IdlePolicy.MaxIdleDurationSeconds != nil {
			if *a.ko.Spec.IdlePolicy.MaxIdleDurationSeconds != *b.ko.Spec.IdlePolicy.MaxIdleDurationSeconds {
				delta.Add("Spec.IdlePolicy.MaxIdleDurationSeconds", a.ko.Spec.IdlePolicy.MaxIdleDurationSeconds, b.ko.Spec.IdlePolicy.MaxIdleDurationSeconds)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.IdlePolicy.SuspendedDurationSeconds, b.ko.Spec.IdlePolicy.SuspendedDurationSeconds) {
			delta.Add("Spec.IdlePolicy.SuspendedDurationSeconds", a.ko.Spec.IdlePolicy.SuspendedDurationSeconds, b.ko.Spec.IdlePolicy.SuspendedDurationSeconds)
		} else if a.ko.Spec.IdlePolicy.SuspendedDurationSeconds != nil && b.ko.Spec.IdlePolicy.SuspendedDurationSeconds != nil {
			if *a.ko.Spec.IdlePolicy.SuspendedDurationSeconds != *b.ko.Spec.IdlePolicy.SuspendedDurationSeconds {
				delta.Add("Spec.IdlePolicy.SuspendedDurationSeconds", a.ko.Spec.IdlePolicy.SuspendedDurationSeconds, b.ko.Spec.IdlePolicy.SuspendedDurationSeconds)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ImageIdentifier, b.ko.Spec.ImageIdentifier) {
		delta.Add("Spec.ImageIdentifier", a.ko.Spec.ImageIdentifier, b.ko.Spec.ImageIdentifier)
	} else if a.ko.Spec.ImageIdentifier != nil && b.ko.Spec.ImageIdentifier != nil {
		if *a.ko.Spec.ImageIdentifier != *b.ko.Spec.ImageIdentifier {
			delta.Add("Spec.ImageIdentifier", a.ko.Spec.ImageIdentifier, b.ko.Spec.ImageIdentifier)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.ImageIdentifierRef, b.ko.Spec.ImageIdentifierRef) {
		delta.Add("Spec.ImageIdentifierRef", a.ko.Spec.ImageIdentifierRef, b.ko.Spec.ImageIdentifierRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ImageVersion, b.ko.Spec.ImageVersion) {
		delta.Add("Spec.ImageVersion", a.ko.Spec.ImageVersion, b.ko.Spec.ImageVersion)
	} else if a.ko.Spec.ImageVersion != nil && b.ko.Spec.ImageVersion != nil {
		if *a.ko.Spec.ImageVersion != *b.ko.Spec.ImageVersion {
			delta.Add("Spec.ImageVersion", a.ko.Spec.ImageVersion, b.ko.Spec.ImageVersion)
		}
	}
	if len(a.ko.Spec.IngressNetworkConnectors) != len(b.ko.Spec.IngressNetworkConnectors) {
		delta.Add("Spec.IngressNetworkConnectors", a.ko.Spec.IngressNetworkConnectors, b.ko.Spec.IngressNetworkConnectors)
	} else if len(a.ko.Spec.IngressNetworkConnectors) > 0 {
		if !ackcompare.SliceStringPEqual(a.ko.Spec.IngressNetworkConnectors, b.ko.Spec.IngressNetworkConnectors) {
			delta.Add("Spec.IngressNetworkConnectors", a.ko.Spec.IngressNetworkConnectors, b.ko.Spec.IngressNetworkConnectors)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Logging, b.ko.Spec.Logging) {
		delta.Add("Spec.Logging", a.ko.Spec.Logging, b.ko.Spec.Logging)
	} else if a.ko.Spec.Logging != nil && b.ko.Spec.Logging != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.Logging.CloudWatch, b.ko.Spec.Logging.CloudWatch) {
			delta.Add("Spec.Logging.CloudWatch", a.ko.Spec.Logging.CloudWatch, b.ko.Spec.Logging.CloudWatch)
		} else if a.ko.Spec.Logging.CloudWatch != nil && b.ko.Spec.Logging.CloudWatch != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.Logging.CloudWatch.LogGroup, b.ko.Spec.Logging.CloudWatch.LogGroup) {
				delta.Add("Spec.Logging.CloudWatch.LogGroup", a.ko.Spec.Logging.CloudWatch.LogGroup, b.ko.Spec.Logging.CloudWatch.LogGroup)
			} else if a.ko.Spec.Logging.CloudWatch.LogGroup != nil && b.ko.Spec.Logging.CloudWatch.LogGroup != nil {
				if *a.ko.Spec.Logging.CloudWatch.LogGroup != *b.ko.Spec.Logging.CloudWatch.LogGroup {
					delta.Add("Spec.Logging.CloudWatch.LogGroup", a.ko.Spec.Logging.CloudWatch.LogGroup, b.ko.Spec.Logging.CloudWatch.LogGroup)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.Logging.CloudWatch.LogStream, b.ko.Spec.Logging.CloudWatch.LogStream) {
				delta.Add("Spec.Logging.CloudWatch.LogStream", a.ko.Spec.Logging.CloudWatch.LogStream, b.ko.Spec.Logging.CloudWatch.LogStream)
			} else if a.ko.Spec.Logging.CloudWatch.LogStream != nil && b.ko.Spec.Logging.CloudWatch.LogStream != nil {
				if *a.ko.Spec.Logging.CloudWatch.LogStream != *b.ko.Spec.Logging.CloudWatch.LogStream {
					delta.Add("Spec.Logging.CloudWatch.LogStream", a.ko.Spec.Logging.CloudWatch.LogStream, b.ko.Spec.Logging.CloudWatch.LogStream)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.Logging.Disabled, b.ko.Spec.Logging.Disabled) {
			delta.Add("Spec.Logging.Disabled", a.ko.Spec.Logging.Disabled, b.ko.Spec.Logging.Disabled)
		} else if a.ko.Spec.Logging.Disabled != nil && b.ko.Spec.Logging.Disabled != nil {
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.MaximumDurationInSeconds, b.ko.Spec.MaximumDurationInSeconds) {
		delta.Add("Spec.MaximumDurationInSeconds", a.ko.Spec.MaximumDurationInSeconds, b.ko.Spec.MaximumDurationInSeconds)
	} else if a.ko.Spec.MaximumDurationInSeconds != nil && b.ko.Spec.MaximumDurationInSeconds != nil {
		if *a.ko.Spec.MaximumDurationInSeconds != *b.ko.Spec.MaximumDurationInSeconds {
			delta.Add("Spec.MaximumDurationInSeconds", a.ko.Spec.MaximumDurationInSeconds, b.ko.Spec.MaximumDurationInSeconds)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.RunHookPayload, b.ko.Spec.RunHookPayload) {
		delta.Add("Spec.RunHookPayload", a.ko.Spec.RunHookPayload, b.ko.Spec.RunHookPayload)
	} else if a.ko.Spec.RunHookPayload != nil && b.ko.Spec.RunHookPayload != nil {
		if *a.ko.Spec.RunHookPayload != *b.ko.Spec.RunHookPayload {
			delta.Add("Spec.RunHookPayload", a.ko.Spec.RunHookPayload, b.ko.Spec.RunHookPayload)
		}
	}

	return delta
}
