// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package microvm

import (
	"context"
	"errors"
	"fmt"
	"math"
	"reflect"
	"strings"
	"time"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	ackutil "github.com/aws-controllers-k8s/runtime/pkg/util"
	"github.com/aws/aws-sdk-go-v2/aws"
	svcsdk "github.com/aws/aws-sdk-go-v2/service/lambdamicrovms"
	svcsdktypes "github.com/aws/aws-sdk-go-v2/service/lambdamicrovms/types"
	smithy "github.com/aws/smithy-go"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/lambdamicrovms-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &svcsdk.Client{}
	_ = &svcapitypes.Microvm{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
	_ = &aws.Config{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.GetMicrovmOutput
	resp, err = rm.sdkapi.GetMicrovm(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "GetMicrovm", err)
	if err != nil {
		var awsErr smithy.APIError
		if errors.As(err, &awsErr) && awsErr.ErrorCode() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if resp.EgressNetworkConnectors != nil {
		ko.Spec.EgressNetworkConnectors = aws.StringSlice(resp.EgressNetworkConnectors)
	} else {
		ko.Spec.EgressNetworkConnectors = nil
	}
	if resp.Endpoint != nil {
		ko.Status.Endpoint = resp.Endpoint
	} else {
		ko.Status.Endpoint = nil
	}
	if resp.ExecutionRoleArn != nil {
		ko.Spec.ExecutionRoleARN = resp.ExecutionRoleArn
	} else {
		ko.Spec.ExecutionRoleARN = nil
	}
	if resp.IdlePolicy != nil {
		f3 := &svcapitypes.IdlePolicy{}
		if resp.IdlePolicy.AutoResumeEnabled != nil {
			f3.AutoResumeEnabled = resp.IdlePolicy.AutoResumeEnabled
		}
		if resp.IdlePolicy.MaxIdleDurationSeconds != nil {
			maxIdleDurationSecondsCopy := int64(*resp.IdlePolicy.MaxIdleDurationSeconds)
			f3.MaxIdleDurationSeconds = &maxIdleDurationSecondsCopy
		}
		if resp.IdlePolicy.SuspendedDurationSeconds != nil {
			suspendedDurationSecondsCopy := int64(*resp.IdlePolicy.SuspendedDurationSeconds)
			f3.SuspendedDurationSeconds = &suspendedDurationSecondsCopy
		}
		ko.Spec.IdlePolicy = f3
	} else {
		ko.Spec.IdlePolicy = nil
	}
	if resp.ImageArn != nil {
		ko.Status.ImageARN = resp.ImageArn
	} else {
		ko.Status.ImageARN = nil
	}
	if resp.ImageVersion != nil {
		ko.Spec.ImageVersion = resp.ImageVersion
	} else {
		ko.Spec.ImageVersion = nil
	}
	if resp.IngressNetworkConnectors != nil {
		ko.Spec.IngressNetworkConnectors = aws.StringSlice(resp.IngressNetworkConnectors)
	} else {
		ko.Spec.IngressNetworkConnectors = nil
	}
	if resp.MaximumDurationInSeconds != nil {
		maximumDurationInSecondsCopy := int64(*resp.MaximumDurationInSeconds)
		ko.Spec.MaximumDurationInSeconds = &maximumDurationInSecondsCopy
	} else {
		ko.Spec.MaximumDurationInSeconds = nil
	}
	if resp.MicrovmId != nil {
		ko.Status.MicrovmID = resp.MicrovmId
	} else {
		ko.Status.MicrovmID = nil
	}
	if resp.StartedAt != nil {
		ko.Status.StartedAt = &metav1.Time{*resp.StartedAt}
	} else {
		ko.Status.StartedAt = nil
	}
	if resp.State != "" {
		ko.Status.State = aws.String(string(resp.State))
	} else {
		ko.Status.State = nil
	}
	if resp.StateReason != nil {
		ko.Status.StateReason = resp.StateReason
	} else {
		ko.Status.StateReason = nil
	}
	if resp.TerminatedAt != nil {
		ko.Status.TerminatedAt = &metav1.Time{*resp.TerminatedAt}
	} else {
		ko.Status.TerminatedAt = nil
	}

	rm.setStatusDefaults(ko)
	if ko.Status.State != nil && *ko.Status.State == string(svcapitypes.MicrovmState_TERMINATED) {
		if !rm.isDeleting(r) {
			msg := "MicroVM terminated unexpectedly (idle policy or max duration exceeded)"
			if ko.Status.StateReason != nil && *ko.Status.StateReason != "" {
				msg = *ko.Status.StateReason
			}
			return &resource{ko}, ackerr.NewTerminalError(errors.New(msg))
		}
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Status.MicrovmID == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.GetMicrovmInput, error) {
	res := &svcsdk.GetMicrovmInput{}

	if r.ko.Status.MicrovmID != nil {
		res.MicrovmIdentifier = r.ko.Status.MicrovmID
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.RunMicrovmOutput
	_ = resp
	resp, err = rm.sdkapi.RunMicrovm(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "RunMicrovm", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.EgressNetworkConnectors != nil {
		ko.Spec.EgressNetworkConnectors = aws.StringSlice(resp.EgressNetworkConnectors)
	} else {
		ko.Spec.EgressNetworkConnectors = nil
	}
	if resp.Endpoint != nil {
		ko.Status.Endpoint = resp.Endpoint
	} else {
		ko.Status.Endpoint = nil
	}
	if resp.ExecutionRoleArn != nil {
		ko.Spec.ExecutionRoleARN = resp.ExecutionRoleArn
	} else {
		ko.Spec.ExecutionRoleARN = nil
	}
	if resp.IdlePolicy != nil {
		f3 := &svcapitypes.IdlePolicy{}
		if resp.IdlePolicy.AutoResumeEnabled != nil {
			f3.AutoResumeEnabled = resp.IdlePolicy.AutoResumeEnabled
		}
		if resp.IdlePolicy.MaxIdleDurationSeconds != nil {
			maxIdleDurationSecondsCopy := int64(*resp.IdlePolicy.MaxIdleDurationSeconds)
			f3.MaxIdleDurationSeconds = &maxIdleDurationSecondsCopy
		}
		if resp.IdlePolicy.SuspendedDurationSeconds != nil {
			suspendedDurationSecondsCopy := int64(*resp.IdlePolicy.SuspendedDurationSeconds)
			f3.SuspendedDurationSeconds = &suspendedDurationSecondsCopy
		}
		ko.Spec.IdlePolicy = f3
	} else {
		ko.Spec.IdlePolicy = nil
	}
	if resp.ImageArn != nil {
		ko.Status.ImageARN = resp.ImageArn
	} else {
		ko.Status.ImageARN = nil
	}
	if resp.ImageVersion != nil {
		ko.Spec.ImageVersion = resp.ImageVersion
	} else {
		ko.Spec.ImageVersion = nil
	}
	if resp.IngressNetworkConnectors != nil {
		ko.Spec.IngressNetworkConnectors = aws.StringSlice(resp.IngressNetworkConnectors)
	} else {
		ko.Spec.IngressNetworkConnectors = nil
	}
	if resp.MaximumDurationInSeconds != nil {
		maximumDurationInSecondsCopy := int64(*resp.MaximumDurationInSeconds)
		ko.Spec.MaximumDurationInSeconds = &maximumDurationInSecondsCopy
	} else {
		ko.Spec.MaximumDurationInSeconds = nil
	}
	if resp.MicrovmId != nil {
		ko.Status.MicrovmID = resp.MicrovmId
	} else {
		ko.Status.MicrovmID = nil
	}
	if resp.StartedAt != nil {
		ko.Status.StartedAt = &metav1.Time{*resp.StartedAt}
	} else {
		ko.Status.StartedAt = nil
	}
	if resp.State != "" {
		ko.Status.State = aws.String(string(resp.State))
	} else {
		ko.Status.State = nil
	}
	if resp.StateReason != nil {
		ko.Status.StateReason = resp.StateReason
	} else {
		ko.Status.StateReason = nil
	}
	if resp.TerminatedAt != nil {
		ko.Status.TerminatedAt = &metav1.Time{*resp.TerminatedAt}
	} else {
		ko.Status.TerminatedAt = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.RunMicrovmInput, error) {
	res := &svcsdk.RunMicrovmInput{}

	if r.ko.Spec.EgressNetworkConnectors != nil {
		res.EgressNetworkConnectors = aws.ToStringSlice(r.ko.Spec.EgressNetworkConnectors)
	}
	if r.ko.Spec.ExecutionRoleARN != nil {
		res.ExecutionRoleArn = r.ko.Spec.ExecutionRoleARN
	}
	if r.ko.Spec.IdlePolicy != nil {
		f3 := &svcsdktypes.IdlePolicy{}
		if r.ko.Spec.IdlePolicy.AutoResumeEnabled != nil {
			f3.AutoResumeEnabled = r.ko.Spec.IdlePolicy.AutoResumeEnabled
		}
		if r.ko.Spec.IdlePolicy.MaxIdleDurationSeconds != nil {
			maxIdleDurationSecondsCopy0 := *r.ko.Spec.IdlePolicy.MaxIdleDurationSeconds
			if maxIdleDurationSecondsCopy0 > math.MaxInt32 || maxIdleDurationSecondsCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field maxIdleDurationSeconds is of type int32")
			}
			maxIdleDurationSecondsCopy := int32(maxIdleDurationSecondsCopy0)
			f3.MaxIdleDurationSeconds = &maxIdleDurationSecondsCopy
		}
		if r.ko.Spec.IdlePolicy.SuspendedDurationSeconds != nil {
			suspendedDurationSecondsCopy0 := *r.ko.Spec.IdlePolicy.SuspendedDurationSeconds
			if suspendedDurationSecondsCopy0 > math.MaxInt32 || suspendedDurationSecondsCopy0 < math.MinInt32 {
				return nil, fmt.Errorf("error: field suspendedDurationSeconds is of type int32")
			}
			suspendedDurationSecondsCopy := int32(suspendedDurationSecondsCopy0)
			f3.SuspendedDurationSeconds = &suspendedDurationSecondsCopy
		}
		res.IdlePolicy = f3
	}
	if r.ko.Spec.ImageIdentifier != nil {
		res.ImageIdentifier = r.ko.Spec.ImageIdentifier
	}
	if r.ko.Spec.ImageVersion != nil {
		res.ImageVersion = r.ko.Spec.ImageVersion
	}
	if r.ko.Spec.IngressNetworkConnectors != nil {
		res.IngressNetworkConnectors = aws.ToStringSlice(r.ko.Spec.IngressNetworkConnectors)
	}
	if r.ko.Spec.Logging != nil {
		var f7 svcsdktypes.Logging
		isInterfaceSet := false
		if r.ko.Spec.Logging.CloudWatch != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for CloudWatch"))
			}
			f7f0Parent := &svcsdktypes.LoggingMemberCloudWatch{}
			f7f0 := &svcsdktypes.CloudWatchLogging{}
			if r.ko.Spec.Logging.CloudWatch.LogGroup != nil {
				f7f0.LogGroup = r.ko.Spec.Logging.CloudWatch.LogGroup
			}
			if r.ko.Spec.Logging.CloudWatch.LogStream != nil {
				f7f0.LogStream = r.ko.Spec.Logging.CloudWatch.LogStream
			}
			f7f0Parent.Value = *f7f0
			f7 = f7f0Parent
			isInterfaceSet = true
		}
		if r.ko.Spec.Logging.Disabled != nil {
			if isInterfaceSet {
				return nil, ackerr.NewTerminalError(fmt.Errorf("can only set one of the members for Disabled"))
			}
			f7f1Parent := &svcsdktypes.LoggingMemberDisabled{}
			f7f1 := &svcsdktypes.LoggingDisabled{}
			f7f1Parent.Value = *f7f1
			f7 = f7f1Parent
			isInterfaceSet = true
		}
		res.Logging = f7
	}
	if r.ko.Spec.MaximumDurationInSeconds != nil {
		maximumDurationInSecondsCopy0 := *r.ko.Spec.MaximumDurationInSeconds
		if maximumDurationInSecondsCopy0 > math.MaxInt32 || maximumDurationInSecondsCopy0 < math.MinInt32 {
			return nil, fmt.Errorf("error: field maximumDurationInSeconds is of type int32")
		}
		maximumDurationInSecondsCopy := int32(maximumDurationInSecondsCopy0)
		res.MaximumDurationInSeconds = &maximumDurationInSecondsCopy
	}
	if r.ko.Spec.RunHookPayload != nil {
		tmpSecret, err := rm.rr.SecretValueFromReference(ctx, r.ko.Spec.RunHookPayload)
		if err != nil {
			return nil, ackrequeue.Needed(err)
		}
		if tmpSecret != "" {
			res.RunHookPayload = aws.String(tmpSecret)
		}
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return nil, ackerr.NewTerminalError(ackerr.NotImplemented)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	// If the VM has already reached TERMINATED there is nothing left to
	// terminate. AWS retains terminated VMs, so GetMicrovm never returns
	// NotFound and the generated delete flow would otherwise requeue forever
	// (the deletable guard also rejects TERMINATED). Treat delete as complete by
	// returning (nil, nil) so the runtime removes the finalizer. TERMINATING and
	// other non-terminal states (e.g. SUSPENDED) deliberately fall through so we
	// never drop the finalizer while the VM might still be alive. See
	// isTerminated in hooks.go for the full rationale.
	if isTerminated(r) {
		return nil, nil
	}

	if r.ko.Status.State != nil {
		if !ackutil.InStrings(*r.ko.Status.State, []string{"RUNNING", "SUSPENDED"}) {
			return nil, ackrequeue.NeededAfter(
				fmt.Errorf("resource is in %s state, cannot be deleted",
					*r.ko.Status.State),
				time.Duration(30)*time.Second,
			)
		}
	}

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.TerminateMicrovmOutput
	_ = resp
	resp, err = rm.sdkapi.TerminateMicrovm(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "TerminateMicrovm", err)
	if err == nil {
		return r, requeueWaitWhileTerminating
	}

	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.TerminateMicrovmInput, error) {
	res := &svcsdk.TerminateMicrovmInput{}

	if r.ko.Status.MicrovmID != nil {
		res.MicrovmIdentifier = r.ko.Status.MicrovmID
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Microvm,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.Partition == nil {
		ko.Status.ACKResourceMetadata.Partition = &rm.awsPartition
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}

	var terminalErr smithy.APIError
	if !errors.As(err, &terminalErr) {
		return false
	}
	switch terminalErr.ErrorCode() {
	case "ValidationException",
		"InvalidParameterValueException":
		return true
	default:
		return false
	}
}
