apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common
  - bases/lambdamicrovms.services.k8s.aws_microvms.yaml
  - bases/lambdamicrovms.services.k8s.aws_microvmimages.yaml
