// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type Architecture string

const (
	Architecture_ARM_64 Architecture = "ARM_64"
)

type BuildState string

const (
	BuildState_FAILED      BuildState = "FAILED"
	BuildState_IN_PROGRESS BuildState = "IN_PROGRESS"
	BuildState_PENDING     BuildState = "PENDING"
	BuildState_SUCCESSFUL  BuildState = "SUCCESSFUL"
)

type Capability string

const (
	Capability_ALL Capability = "ALL"
)

type Chipset string

const (
	Chipset_GRAVITON Chipset = "GRAVITON"
)

type HookState string

const (
	HookState_DISABLED HookState = "DISABLED"
	HookState_ENABLED  HookState = "ENABLED"
)

type MicrovmImageState string

const (
	MicrovmImageState_CREATED       MicrovmImageState = "CREATED"
	MicrovmImageState_CREATE_FAILED MicrovmImageState = "CREATE_FAILED"
	MicrovmImageState_CREATING      MicrovmImageState = "CREATING"
	MicrovmImageState_DELETED       MicrovmImageState = "DELETED"
	MicrovmImageState_DELETE_FAILED MicrovmImageState = "DELETE_FAILED"
	MicrovmImageState_DELETING      MicrovmImageState = "DELETING"
	MicrovmImageState_UPDATED       MicrovmImageState = "UPDATED"
	MicrovmImageState_UPDATE_FAILED MicrovmImageState = "UPDATE_FAILED"
	MicrovmImageState_UPDATING      MicrovmImageState = "UPDATING"
)

type MicrovmImageVersionState string

const (
	MicrovmImageVersionState_DELETED       MicrovmImageVersionState = "DELETED"
	MicrovmImageVersionState_DELETE_FAILED MicrovmImageVersionState = "DELETE_FAILED"
	MicrovmImageVersionState_DELETING      MicrovmImageVersionState = "DELETING"
	MicrovmImageVersionState_FAILED        MicrovmImageVersionState = "FAILED"
	MicrovmImageVersionState_IN_PROGRESS   MicrovmImageVersionState = "IN_PROGRESS"
	MicrovmImageVersionState_PENDING       MicrovmImageVersionState = "PENDING"
	MicrovmImageVersionState_SUCCESSFUL    MicrovmImageVersionState = "SUCCESSFUL"
)

type MicrovmImageVersionStatus string

const (
	MicrovmImageVersionStatus_ACTIVE   MicrovmImageVersionStatus = "ACTIVE"
	MicrovmImageVersionStatus_INACTIVE MicrovmImageVersionStatus = "INACTIVE"
)

type MicrovmState string

const (
	MicrovmState_PENDING     MicrovmState = "PENDING"
	MicrovmState_RUNNING     MicrovmState = "RUNNING"
	MicrovmState_SUSPENDED   MicrovmState = "SUSPENDED"
	MicrovmState_SUSPENDING  MicrovmState = "SUSPENDING"
	MicrovmState_TERMINATED  MicrovmState = "TERMINATED"
	MicrovmState_TERMINATING MicrovmState = "TERMINATING"
)
