// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MicrovmImageSpec defines the desired state of MicrovmImage.
type MicrovmImageSpec struct {

	// Additional OS capabilities granted to the MicroVM runtime environment.
	AdditionalOsCapabilities []*string `json:"additionalOsCapabilities,omitempty"`
	// The ARN of the Lambda-managed base MicroVM image to build upon. Use ListManagedMicrovmImages
	// to discover available base images.
	//
	// Regex Pattern: `^[^\s]+$`
	// +kubebuilder:validation:Required
	BaseImageARN *string `json:"baseImageARN"`
	// The specific version of the base MicroVM image to use.
	//
	// Regex Pattern: `^[^\s]+$`
	BaseImageVersion *string `json:"baseImageVersion,omitempty"`
	// The ARN of the IAM role assumed during the image build process. This role
	// must have permissions to access the code artifact and any required resources.
	//
	// Regex Pattern: `^arn:aws[a-z\-]*:iam::[0-9]{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$`
	BuildRoleARN *string                                  `json:"buildRoleARN,omitempty"`
	BuildRoleRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"buildRoleRef,omitempty"`
	// The code artifact containing the application code and metadata for the MicroVM
	// image.
	// +kubebuilder:validation:Required
	CodeArtifact *CodeArtifact `json:"codeArtifact"`
	// The list of supported CPU configurations for the MicroVM.
	CPUConfigurations []*CPUConfiguration `json:"cpuConfigurations,omitempty"`
	// A description of the MicroVM image.
	Description *string `json:"description,omitempty"`
	// The list of egress network connectors available to the MicroVM at runtime.
	EgressNetworkConnectors []*string `json:"egressNetworkConnectors,omitempty"`
	// Environment variables set in the MicroVM runtime environment.
	EnvironmentVariables map[string]*string `json:"environmentVariables,omitempty"`
	Hooks                *Hooks             `json:"hooks,omitempty"`
	// The logging configuration for build-time and runtime logs. Specify {"cloudWatch":
	// {"logGroup": "..."}} to stream logs to a custom CloudWatch log group, or
	// {"disabled": {}} to turn off logging.
	Logging *Logging `json:"logging,omitempty"`
	// The name of the MicroVM image. Must be unique within the AWS account.
	//
	// Regex Pattern: `^[a-zA-Z0-9-_]+$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Name *string `json:"name"`
	// The resource requirements for the MicroVM.
	Resources []*Resources `json:"resources,omitempty"`
	// A set of key-value pairs that you can attach to the resource. Use tags to
	// categorize resources for cost allocation, access control (ABAC), and organization.
	Tags map[string]*string `json:"tags,omitempty"`
}

// MicrovmImageStatus defines the observed state of MicrovmImage
type MicrovmImageStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The timestamp when the MicroVM image was created.
	// +kubebuilder:validation:Optional
	CreatedAt *metav1.Time `json:"createdAt,omitempty"`
	// The version of the MicroVM image.
	//
	// Regex Pattern: `^[^\s]+$`
	// +kubebuilder:validation:Optional
	ImageVersion *string `json:"imageVersion,omitempty"`
	// The latest active version of the MicroVM image.
	//
	// Regex Pattern: `^[^\s]+$`
	// +kubebuilder:validation:Optional
	LatestActiveImageVersion *string `json:"latestActiveImageVersion,omitempty"`
	// The latest failed version of the MicroVM image, if any.
	//
	// Regex Pattern: `^[^\s]+$`
	// +kubebuilder:validation:Optional
	LatestFailedImageVersion *string `json:"latestFailedImageVersion,omitempty"`
	// The specific version of the base MicroVM image.
	//
	// Regex Pattern: `^[^\s]+$`
	// +kubebuilder:validation:Optional
	ResolvedBaseImageVersion *string `json:"resolvedBaseImageVersion,omitempty"`
	// The current state of the MicroVM image.
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty"`
	// The timestamp when the MicroVM image was last updated.
	// +kubebuilder:validation:Optional
	UpdatedAt *metav1.Time `json:"updatedAt,omitempty"`
}

// MicrovmImage is the Schema for the MicrovmImages API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type MicrovmImage struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              MicrovmImageSpec   `json:"spec,omitempty"`
	Status            MicrovmImageStatus `json:"status,omitempty"`
}

// MicrovmImageList contains a list of MicrovmImage
// +kubebuilder:object:root=true
type MicrovmImageList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MicrovmImage `json:"items"`
}

func init() {
	SchemeBuilder.Register(&MicrovmImage{}, &MicrovmImageList{})
}
