// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MicrovmSpec defines the desired state of Microvm.
type MicrovmSpec struct {

	// The list of egress network connectors to configure for the MicroVM.
	EgressNetworkConnectors []*string `json:"egressNetworkConnectors,omitempty"`
	// The ARN of the IAM role to be assumed by the MicroVM during execution.
	//
	// Regex Pattern: `^arn:aws[a-z\-]*:iam::[0-9]{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$`
	ExecutionRoleARN *string                                  `json:"executionRoleARN,omitempty"`
	ExecutionRoleRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"executionRoleRef,omitempty"`
	// Configuration to control auto-suspend and auto-resume behavior.
	IdlePolicy *IdlePolicy `json:"idlePolicy,omitempty"`
	// The identifier (ARN or ID) of the MicroVM image to run.
	ImageIdentifier    *string                                  `json:"imageIdentifier,omitempty"`
	ImageIdentifierRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"imageIdentifierRef,omitempty"`
	// The version of the MicroVM image to run.
	//
	// Regex Pattern: `^[^\s]+$`
	ImageVersion *string `json:"imageVersion,omitempty"`
	// The list of ingress network connectors to configure for the MicroVM.
	IngressNetworkConnectors []*string `json:"ingressNetworkConnectors,omitempty"`
	// The logging configuration for this MicroVM instance. Specify {"cloudWatch":
	// {"logGroup": "..."}} to stream application logs to a custom CloudWatch log
	// group, or {"disabled": {}} to turn off logging.
	Logging *Logging `json:"logging,omitempty"`
	// The maximum duration in seconds that the MicroVM can exist before being terminated
	// by the platform. Valid range: 1–28,800 (8 hours).
	MaximumDurationInSeconds *int64 `json:"maximumDurationInSeconds,omitempty"`
	// Per-MicroVM initialization data delivered as the request body of the /run
	// lifecycle hook. Use to pass tenant-specific configuration such as session
	// IDs or secret references. Maximum: 16,384 bytes.
	RunHookPayload *ackv1alpha1.SecretKeyReference `json:"runHookPayload,omitempty"`
}

// MicrovmStatus defines the observed state of Microvm
type MicrovmStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The HTTPS endpoint URL for communicating with the MicroVM. Include a valid
	// authentication token in the X-aws-proxy-auth header when sending requests.
	// +kubebuilder:validation:Optional
	Endpoint *string `json:"endpoint,omitempty"`
	// The ARN of the MicroVM image used to run this MicroVM.
	// +kubebuilder:validation:Optional
	ImageARN *string `json:"imageARN,omitempty"`
	// The unique identifier of the MicroVM.
	// +kubebuilder:validation:Optional
	MicrovmID *string `json:"microvmID,omitempty"`
	// The timestamp when the MicroVM first started.
	// +kubebuilder:validation:Optional
	StartedAt *metav1.Time `json:"startedAt,omitempty"`
	// The current lifecycle state of the MicroVM.
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty"`
	// The reason for why the MicroVM is in the current state.
	//
	// Regex Pattern: `^[^\s]+$`
	// +kubebuilder:validation:Optional
	StateReason *string `json:"stateReason,omitempty"`
	// The timestamp when the MicroVM terminated.
	// +kubebuilder:validation:Optional
	TerminatedAt *metav1.Time `json:"terminatedAt,omitempty"`
}

// Microvm is the Schema for the Microvms API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="MICROVM-ID",type=string,priority=0,JSONPath=`.status.microvmID`
type Microvm struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              MicrovmSpec   `json:"spec,omitempty"`
	Status            MicrovmStatus `json:"status,omitempty"`
}

// MicrovmList contains a list of Microvm
// +kubebuilder:object:root=true
type MicrovmList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Microvm `json:"items"`
}

func init() {
	SchemeBuilder.Register(&Microvm{}, &MicrovmList{})
}
