//go:build !ignore_autogenerated

// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUConfiguration) DeepCopyInto(out *CPUConfiguration) {
	*out = *in
	if in.Architecture != nil {
		in, out := &in.Architecture, &out.Architecture
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUConfiguration.
func (in *CPUConfiguration) DeepCopy() *CPUConfiguration {
	if in == nil {
		return nil
	}
	out := new(CPUConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudWatchLogging) DeepCopyInto(out *CloudWatchLogging) {
	*out = *in
	if in.LogGroup != nil {
		in, out := &in.LogGroup, &out.LogGroup
		*out = new(string)
		**out = **in
	}
	if in.LogStream != nil {
		in, out := &in.LogStream, &out.LogStream
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudWatchLogging.
func (in *CloudWatchLogging) DeepCopy() *CloudWatchLogging {
	if in == nil {
		return nil
	}
	out := new(CloudWatchLogging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeArtifact) DeepCopyInto(out *CodeArtifact) {
	*out = *in
	if in.URI != nil {
		in, out := &in.URI, &out.URI
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeArtifact.
func (in *CodeArtifact) DeepCopy() *CodeArtifact {
	if in == nil {
		return nil
	}
	out := new(CodeArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Hooks) DeepCopyInto(out *Hooks) {
	*out = *in
	if in.MicrovmHooks != nil {
		in, out := &in.MicrovmHooks, &out.MicrovmHooks
		*out = new(MicrovmHooks)
		(*in).DeepCopyInto(*out)
	}
	if in.MicrovmImageHooks != nil {
		in, out := &in.MicrovmImageHooks, &out.MicrovmImageHooks
		*out = new(MicrovmImageHooks)
		(*in).DeepCopyInto(*out)
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Hooks.
func (in *Hooks) DeepCopy() *Hooks {
	if in == nil {
		return nil
	}
	out := new(Hooks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdlePolicy) DeepCopyInto(out *IdlePolicy) {
	*out = *in
	if in.AutoResumeEnabled != nil {
		in, out := &in.AutoResumeEnabled, &out.AutoResumeEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MaxIdleDurationSeconds != nil {
		in, out := &in.MaxIdleDurationSeconds, &out.MaxIdleDurationSeconds
		*out = new(int64)
		**out = **in
	}
	if in.SuspendedDurationSeconds != nil {
		in, out := &in.SuspendedDurationSeconds, &out.SuspendedDurationSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdlePolicy.
func (in *IdlePolicy) DeepCopy() *IdlePolicy {
	if in == nil {
		return nil
	}
	out := new(IdlePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Logging) DeepCopyInto(out *Logging) {
	*out = *in
	if in.CloudWatch != nil {
		in, out := &in.CloudWatch, &out.CloudWatch
		*out = new(CloudWatchLogging)
		(*in).DeepCopyInto(*out)
	}
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Logging.
func (in *Logging) DeepCopy() *Logging {
	if in == nil {
		return nil
	}
	out := new(Logging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedMicrovmImageSummary) DeepCopyInto(out *ManagedMicrovmImageSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.ImageARN != nil {
		in, out := &in.ImageARN, &out.ImageARN
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedMicrovmImageSummary.
func (in *ManagedMicrovmImageSummary) DeepCopy() *ManagedMicrovmImageSummary {
	if in == nil {
		return nil
	}
	out := new(ManagedMicrovmImageSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedMicrovmImageVersion) DeepCopyInto(out *ManagedMicrovmImageVersion) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.ImageARN != nil {
		in, out := &in.ImageARN, &out.ImageARN
		*out = new(string)
		**out = **in
	}
	if in.ImageVersion != nil {
		in, out := &in.ImageVersion, &out.ImageVersion
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedMicrovmImageVersion.
func (in *ManagedMicrovmImageVersion) DeepCopy() *ManagedMicrovmImageVersion {
	if in == nil {
		return nil
	}
	out := new(ManagedMicrovmImageVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Microvm) DeepCopyInto(out *Microvm) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Microvm.
func (in *Microvm) DeepCopy() *Microvm {
	if in == nil {
		return nil
	}
	out := new(Microvm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Microvm) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicrovmHooks) DeepCopyInto(out *MicrovmHooks) {
	*out = *in
	if in.Resume != nil {
		in, out := &in.Resume, &out.Resume
		*out = new(string)
		**out = **in
	}
	if in.ResumeTimeoutInSeconds != nil {
		in, out := &in.ResumeTimeoutInSeconds, &out.ResumeTimeoutInSeconds
		*out = new(int64)
		**out = **in
	}
	if in.Run != nil {
		in, out := &in.Run, &out.Run
		*out = new(string)
		**out = **in
	}
	if in.RunTimeoutInSeconds != nil {
		in, out := &in.RunTimeoutInSeconds, &out.RunTimeoutInSeconds
		*out = new(int64)
		**out = **in
	}
	if in.Suspend != nil {
		in, out := &in.Suspend, &out.Suspend
		*out = new(string)
		**out = **in
	}
	if in.SuspendTimeoutInSeconds != nil {
		in, out := &in.SuspendTimeoutInSeconds, &out.SuspendTimeoutInSeconds
		*out = new(int64)
		**out = **in
	}
	if in.Terminate != nil {
		in, out := &in.Terminate, &out.Terminate
		*out = new(string)
		**out = **in
	}
	if in.TerminateTimeoutInSeconds != nil {
		in, out := &in.TerminateTimeoutInSeconds, &out.TerminateTimeoutInSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicrovmHooks.
func (in *MicrovmHooks) DeepCopy() *MicrovmHooks {
	if in == nil {
		return nil
	}
	out := new(MicrovmHooks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicrovmImage) DeepCopyInto(out *MicrovmImage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicrovmImage.
func (in *MicrovmImage) DeepCopy() *MicrovmImage {
	if in == nil {
		return nil
	}
	out := new(MicrovmImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicrovmImage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicrovmImageBuildSummary) DeepCopyInto(out *MicrovmImageBuildSummary) {
	*out = *in
	if in.Architecture != nil {
		in, out := &in.Architecture, &out.Architecture
		*out = new(string)
		**out = **in
	}
	if in.BuildID != nil {
		in, out := &in.BuildID, &out.BuildID
		*out = new(string)
		**out = **in
	}
	if in.ChipsetGeneration != nil {
		in, out := &in.ChipsetGeneration, &out.ChipsetGeneration
		*out = new(string)
		**out = **in
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.ImageARN != nil {
		in, out := &in.ImageARN, &out.ImageARN
		*out = new(string)
		**out = **in
	}
	if in.ImageVersion != nil {
		in, out := &in.ImageVersion, &out.ImageVersion
		*out = new(string)
		**out = **in
	}
	if in.StateReason != nil {
		in, out := &in.StateReason, &out.StateReason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicrovmImageBuildSummary.
func (in *MicrovmImageBuildSummary) DeepCopy() *MicrovmImageBuildSummary {
	if in == nil {
		return nil
	}
	out := new(MicrovmImageBuildSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicrovmImageHooks) DeepCopyInto(out *MicrovmImageHooks) {
	*out = *in
	if in.Ready != nil {
		in, out := &in.Ready, &out.Ready
		*out = new(string)
		**out = **in
	}
	if in.ReadyTimeoutInSeconds != nil {
		in, out := &in.ReadyTimeoutInSeconds, &out.ReadyTimeoutInSeconds
		*out = new(int64)
		**out = **in
	}
	if in.Validate != nil {
		in, out := &in.Validate, &out.Validate
		*out = new(string)
		**out = **in
	}
	if in.ValidateTimeoutInSeconds != nil {
		in, out := &in.ValidateTimeoutInSeconds, &out.ValidateTimeoutInSeconds
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicrovmImageHooks.
func (in *MicrovmImageHooks) DeepCopy() *MicrovmImageHooks {
	if in == nil {
		return nil
	}
	out := new(MicrovmImageHooks)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicrovmImageList) DeepCopyInto(out *MicrovmImageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MicrovmImage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicrovmImageList.
func (in *MicrovmImageList) DeepCopy() *MicrovmImageList {
	if in == nil {
		return nil
	}
	out := new(MicrovmImageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicrovmImageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicrovmImageSpec) DeepCopyInto(out *MicrovmImageSpec) {
	*out = *in
	if in.AdditionalOsCapabilities != nil {
		in, out := &in.AdditionalOsCapabilities, &out.AdditionalOsCapabilities
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.BaseImageARN != nil {
		in, out := &in.BaseImageARN, &out.BaseImageARN
		*out = new(string)
		**out = **in
	}
	if in.BaseImageVersion != nil {
		in, out := &in.BaseImageVersion, &out.BaseImageVersion
		*out = new(string)
		**out = **in
	}
	if in.BuildRoleARN != nil {
		in, out := &in.BuildRoleARN, &out.BuildRoleARN
		*out = new(string)
		**out = **in
	}
	if in.BuildRoleRef != nil {
		in, out := &in.BuildRoleRef, &out.BuildRoleRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.CodeArtifact != nil {
		in, out := &in.CodeArtifact, &out.CodeArtifact
		*out = new(CodeArtifact)
		(*in).DeepCopyInto(*out)
	}
	if in.CPUConfigurations != nil {
		in, out := &in.CPUConfigurations, &out.CPUConfigurations
		*out = make([]*CPUConfiguration, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(CPUConfiguration)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EgressNetworkConnectors != nil {
		in, out := &in.EgressNetworkConnectors, &out.EgressNetworkConnectors
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.EnvironmentVariables != nil {
		in, out := &in.EnvironmentVariables, &out.EnvironmentVariables
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Hooks != nil {
		in, out := &in.Hooks, &out.Hooks
		*out = new(Hooks)
		(*in).DeepCopyInto(*out)
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(Logging)
		(*in).DeepCopyInto(*out)
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]*Resources, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Resources)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicrovmImageSpec.
func (in *MicrovmImageSpec) DeepCopy() *MicrovmImageSpec {
	if in == nil {
		return nil
	}
	out := new(MicrovmImageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicrovmImageStatus) DeepCopyInto(out *MicrovmImageStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.ImageVersion != nil {
		in, out := &in.ImageVersion, &out.ImageVersion
		*out = new(string)
		**out = **in
	}
	if in.LatestActiveImageVersion != nil {
		in, out := &in.LatestActiveImageVersion, &out.LatestActiveImageVersion
		*out = new(string)
		**out = **in
	}
	if in.LatestFailedImageVersion != nil {
		in, out := &in.LatestFailedImageVersion, &out.LatestFailedImageVersion
		*out = new(string)
		**out = **in
	}
	if in.ResolvedBaseImageVersion != nil {
		in, out := &in.ResolvedBaseImageVersion, &out.ResolvedBaseImageVersion
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicrovmImageStatus.
func (in *MicrovmImageStatus) DeepCopy() *MicrovmImageStatus {
	if in == nil {
		return nil
	}
	out := new(MicrovmImageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicrovmImageSummary) DeepCopyInto(out *MicrovmImageSummary) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.ImageARN != nil {
		in, out := &in.ImageARN, &out.ImageARN
		*out = new(string)
		**out = **in
	}
	if in.LatestActiveImageVersion != nil {
		in, out := &in.LatestActiveImageVersion, &out.LatestActiveImageVersion
		*out = new(string)
		**out = **in
	}
	if in.LatestFailedImageVersion != nil {
		in, out := &in.LatestFailedImageVersion, &out.LatestFailedImageVersion
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicrovmImageSummary.
func (in *MicrovmImageSummary) DeepCopy() *MicrovmImageSummary {
	if in == nil {
		return nil
	}
	out := new(MicrovmImageSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicrovmImageVersionSummary) DeepCopyInto(out *MicrovmImageVersionSummary) {
	*out = *in
	if in.AdditionalOsCapabilities != nil {
		in, out := &in.AdditionalOsCapabilities, &out.AdditionalOsCapabilities
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.BaseImageARN != nil {
		in, out := &in.BaseImageARN, &out.BaseImageARN
		*out = new(string)
		**out = **in
	}
	if in.BaseImageVersion != nil {
		in, out := &in.BaseImageVersion, &out.BaseImageVersion
		*out = new(string)
		**out = **in
	}
	if in.BuildRoleARN != nil {
		in, out := &in.BuildRoleARN, &out.BuildRoleARN
		*out = new(string)
		**out = **in
	}
	if in.CodeArtifact != nil {
		in, out := &in.CodeArtifact, &out.CodeArtifact
		*out = new(CodeArtifact)
		(*in).DeepCopyInto(*out)
	}
	if in.CPUConfigurations != nil {
		in, out := &in.CPUConfigurations, &out.CPUConfigurations
		*out = make([]*CPUConfiguration, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(CPUConfiguration)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EgressNetworkConnectors != nil {
		in, out := &in.EgressNetworkConnectors, &out.EgressNetworkConnectors
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.EnvironmentVariables != nil {
		in, out := &in.EnvironmentVariables, &out.EnvironmentVariables
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Hooks != nil {
		in, out := &in.Hooks, &out.Hooks
		*out = new(Hooks)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageARN != nil {
		in, out := &in.ImageARN, &out.ImageARN
		*out = new(string)
		**out = **in
	}
	if in.ImageVersion != nil {
		in, out := &in.ImageVersion, &out.ImageVersion
		*out = new(string)
		**out = **in
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(Logging)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]*Resources, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Resources)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.StateReason != nil {
		in, out := &in.StateReason, &out.StateReason
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicrovmImageVersionSummary.
func (in *MicrovmImageVersionSummary) DeepCopy() *MicrovmImageVersionSummary {
	if in == nil {
		return nil
	}
	out := new(MicrovmImageVersionSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicrovmItem) DeepCopyInto(out *MicrovmItem) {
	*out = *in
	if in.ImageARN != nil {
		in, out := &in.ImageARN, &out.ImageARN
		*out = new(string)
		**out = **in
	}
	if in.ImageVersion != nil {
		in, out := &in.ImageVersion, &out.ImageVersion
		*out = new(string)
		**out = **in
	}
	if in.MicrovmID != nil {
		in, out := &in.MicrovmID, &out.MicrovmID
		*out = new(string)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicrovmItem.
func (in *MicrovmItem) DeepCopy() *MicrovmItem {
	if in == nil {
		return nil
	}
	out := new(MicrovmItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicrovmList) DeepCopyInto(out *MicrovmList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Microvm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicrovmList.
func (in *MicrovmList) DeepCopy() *MicrovmList {
	if in == nil {
		return nil
	}
	out := new(MicrovmList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MicrovmList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicrovmSpec) DeepCopyInto(out *MicrovmSpec) {
	*out = *in
	if in.EgressNetworkConnectors != nil {
		in, out := &in.EgressNetworkConnectors, &out.EgressNetworkConnectors
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ExecutionRoleARN != nil {
		in, out := &in.ExecutionRoleARN, &out.ExecutionRoleARN
		*out = new(string)
		**out = **in
	}
	if in.ExecutionRoleRef != nil {
		in, out := &in.ExecutionRoleRef, &out.ExecutionRoleRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.IdlePolicy != nil {
		in, out := &in.IdlePolicy, &out.IdlePolicy
		*out = new(IdlePolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageIdentifier != nil {
		in, out := &in.ImageIdentifier, &out.ImageIdentifier
		*out = new(string)
		**out = **in
	}
	if in.ImageIdentifierRef != nil {
		in, out := &in.ImageIdentifierRef, &out.ImageIdentifierRef
		*out = new(corev1alpha1.AWSResourceReferenceWrapper)
		(*in).DeepCopyInto(*out)
	}
	if in.ImageVersion != nil {
		in, out := &in.ImageVersion, &out.ImageVersion
		*out = new(string)
		**out = **in
	}
	if in.IngressNetworkConnectors != nil {
		in, out := &in.IngressNetworkConnectors, &out.IngressNetworkConnectors
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(Logging)
		(*in).DeepCopyInto(*out)
	}
	if in.MaximumDurationInSeconds != nil {
		in, out := &in.MaximumDurationInSeconds, &out.MaximumDurationInSeconds
		*out = new(int64)
		**out = **in
	}
	if in.RunHookPayload != nil {
		in, out := &in.RunHookPayload, &out.RunHookPayload
		*out = new(corev1alpha1.SecretKeyReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicrovmSpec.
func (in *MicrovmSpec) DeepCopy() *MicrovmSpec {
	if in == nil {
		return nil
	}
	out := new(MicrovmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicrovmStatus) DeepCopyInto(out *MicrovmStatus) {
	*out = *in
	if in.ACKResourceMetadata != nil {
		in, out := &in.ACKResourceMetadata, &out.ACKResourceMetadata
		*out = new(corev1alpha1.ResourceMetadata)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*corev1alpha1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(corev1alpha1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.ImageARN != nil {
		in, out := &in.ImageARN, &out.ImageARN
		*out = new(string)
		**out = **in
	}
	if in.MicrovmID != nil {
		in, out := &in.MicrovmID, &out.MicrovmID
		*out = new(string)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.StateReason != nil {
		in, out := &in.StateReason, &out.StateReason
		*out = new(string)
		**out = **in
	}
	if in.TerminatedAt != nil {
		in, out := &in.TerminatedAt, &out.TerminatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicrovmStatus.
func (in *MicrovmStatus) DeepCopy() *MicrovmStatus {
	if in == nil {
		return nil
	}
	out := new(MicrovmStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resources) DeepCopyInto(out *Resources) {
	*out = *in
	if in.MinimumMemoryInMiB != nil {
		in, out := &in.MinimumMemoryInMiB, &out.MinimumMemoryInMiB
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resources.
func (in *Resources) DeepCopy() *Resources {
	if in == nil {
		return nil
	}
	out := new(Resources)
	in.DeepCopyInto(out)
	return out
}
